### PR TITLE
Updates KPP module

### PR DESCRIPTION
**Pull request by gustavo-marques**
The main purposes of this PR is to update the KPP module. MOM6 was blowing up when MatchTechnique = 'MatchBoth' in CVMix_init_kpp (due to negative viscosities/diffusivities).This was happening because two parameters in `CVMix_init_kpp`, `interp_type` and `interp_type2`, were being controlled by the same MOM6 input parameter, **INTERP_TYPE** ( linear, quadratic or cubic).  These should not be controlled by the same parameter since they have different options in CVMix, e.g., interp_type = linear, quadratic or cubic; while interp_type2 = linear, quadratic, cubic or LMD94. 
This PR fixes that by introducing a new parameter, **INTERP_TYPE2**.  It was also noticed that parameter `lnoDGat1` was not being set in the MOM6 call to `CVMix_init_kpp` (CVMix sets lnoDGat1=True by default, G'(1) = 0 shape function, i.e., gradient is not matched). We, therefore, modified the code such that when MatchTechnique = 'ParabolicNonLocal' .or. MatchTechnique = 'SimpleShapes', lnoDGat1=true. Otherwise, lnoDGat1=false.

### Additional changes:
* option to smooth the boundary layer depth 
* option to smooth the gradient Richardson #
* fix a typo in ocn_comp_mct.F90
* rename MOM_KPP.F90 -> MOM_CVMix_KPP.F90
* computes diffusivity for salt and heat separetely

This PR change answers (dev-master-candidate-2018-06-03) for test case **ocean_only/SCM_idealized_hurricane**. Old answers can be obtained by adding `INTERP_TYPE = "cubic"` into the MOM_KPP section of MOM_input. Answers for other tests are not changed (only intel was tested).

### CODE REVIEW

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/4767

**Comment by adcroft** [comment]
This passes our tests at GFDL after making the one change to SCM_idealized_hurricane test.

I'll wait to hear from @kshedstrom, @jiandewang, and @awallcraft before accepting the PR to dev/master.

**Comment by kshedstrom** [comment]
I approve this pull request, though I did have to deal with a few merge conflicts from some recent GFDL formatting changes.

**Comment by adcroft** [comment]
Yes there will be conflicts with dev/gfdl but the merge to dev/master was clean.

**Comment by awallcraft** [comment]
I am not setup to evaluate pull requests, so I approve without testing.

**Pull request merged**
