### PR TITLE
New TC variants

### PR DESCRIPTION
**Pull request by adcroft**
- Added second variants of tc1
- Added variant of tc2

### CODE REVIEW

**Comment by adcroft** [comment]
This is where the time is/will be spent with this PR. tc2 is long (11s per test on gaea, 15s on Tavis-CI) and adding a variant adds 90s to testing total time. To get full coverage will be expensive so we need to figure out how to exercise code in fewer steps. I'm think non-zero initialization with large numbers might do it?
```
tc0.asymmetric: 	 0.219610
tc0.dim.h: 	 0.265081
tc0.dim.l: 	 0.243992
tc0.dim.t: 	 0.403336
tc0.dim.z: 	 0.229000
tc0.layout: 	 0.323182
tc0.nan: 	 0.301176
tc0.repro: 	 0.209885
tc0.restart1: 	 0.289690
tc0.restart2: 	 0.382158
tc0.symmetric: 	 0.626334
tc1.a.asymmetric: 	 3.835315
tc1.a.dim.h: 	 3.909432
tc1.a.dim.l: 	 3.916244
tc1.a.dim.t: 	 4.113908
tc1.a.dim.z: 	 3.908924
tc1.a.layout: 	 2.684047
tc1.a.nan: 	 4.028140
tc1.a.repro: 	 3.486330
tc1.a.restart1: 	 2.109182
tc1.a.restart2: 	 2.217560
tc1.a.symmetric: 	 4.259010
tc1.asymmetric: 	 4.846526
tc1.b.asymmetric: 	 3.244925
tc1.b.dim.h: 	 3.332088
tc1.b.dim.l: 	 3.270622
tc1.b.dim.t: 	 3.745655
tc1.b.dim.z: 	 3.323972
tc1.b.layout: 	 2.265830
tc1.b.nan: 	 3.376866
tc1.b.repro: 	 2.941922
tc1.b.restart1: 	 1.788271
tc1.b.restart2: 	 1.955641
tc1.b.symmetric: 	 3.565310
tc1.dim.h: 	 5.428959
tc1.dim.l: 	 5.196707
tc1.dim.t: 	 5.378988
tc1.dim.z: 	 5.119642
tc1.layout: 	 3.516559
tc1.nan: 	 5.247020
tc1.repro: 	 4.675445
tc1.restart1: 	 2.697164
tc1.restart2: 	 2.794426
tc1.symmetric: 	 5.443705
tc2.a.asymmetric: 	 11.001344
tc2.a.dim.h: 	 11.251322
tc2.a.dim.l: 	 11.252902
tc2.a.dim.t: 	 11.296298
tc2.a.dim.z: 	 11.248118
tc2.a.layout: 	 7.203558
tc2.a.nan: 	 11.295719
tc2.a.repro: 	 10.171971
tc2.a.restart1: 	 5.815618
tc2.a.restart2: 	 5.853445
tc2.a.symmetric: 	 11.386333
tc2.asymmetric: 	 10.625184
tc2.dim.h: 	 11.209334
tc2.dim.l: 	 11.194546
tc2.dim.t: 	 11.372030
tc2.dim.z: 	 11.144258
tc2.layout: 	 7.035526
tc2.nan: 	 11.224044
tc2.repro: 	 10.066844
tc2.restart1: 	 5.904596
tc2.restart2: 	 5.819918
tc2.symmetric: 	 11.291526
tc3.dim.h: 	 2.296441
tc3.dim.l: 	 2.303803
tc3.dim.t: 	 2.389691
tc3.dim.z: 	 2.319657
tc3.layout: 	 1.606069
tc3.nan: 	 2.398817
tc3.repro: 	 2.000175
tc3.restart1: 	 1.279842
tc3.restart2: 	 1.362599
tc3.symmetric: 	 2.538667
```

**Comment by marshallward** [comment]
Looking at tc1 vs t2, seems like just the diagnostic mediator alone is 4 seconds longer (6.8 vs 2.8).The rest seems to be 2 sec more in traver advection.

I guess ALE is just doing more work here?  Also the diagnostics may be more expensive because of layer remapping?

**Comment by adcroft** [comment]
> Looking at tc1 vs t2, seems like just the diagnostic mediator alone is 4 seconds longer (6.8 vs 2.8).The rest seems to be 2 sec more in traver advection.
> 
> I guess ALE is just doing more work here? Also the diagnostics may be more expensive because of layer remapping?

It's also that we turned on all the parameterizations, tides, etc. tc1 is quite simple by comparison.

**Comment by adcroft** [comment]
Actually, I think it's because half the points in tc1 are masked i.e. dry and not computed!

Depth:
image
Wet:
image

**Comment by marshallward** [comment]
Performance aside, this all worked for me, and it also did not create any new diagnostic errors, so should be OK to merge.

This does not affect the code or answers so does not require a formal regression test on Gaea.

**Comment by marshallward** [comment]
Sorry, I just clicked on some "Ready for Review" feature which was probably meant for you @adcroft.  Is this "ready for review" and merge?

**Comment by adcroft** [comment]
@marshallward I had used the "Draft pull request" option because this was exploratory. Given how much more time is taken for so little coverage gained I think we need to have a hard think about whether the ".a", ".b" derivatives are worth it. There's a "_tc4" waiting to be added too and it only checks an additional hand full of lines. It would be better to replace tc3 with _tc4 and convert tc2.a and tc2.b into full TCs with as many options changed as possible. Let's talk ...

**Comment by marshallward** [comment]
Sounds like despite the possible inefficiencies, that we should keep marching towards better coverage and so should go ahead and merge this.

**Comment by marshallward** [comment]
This passed on Travis but the `tc2.a` OpenMP test failed on my laptop.  The first diff is in the `MOM_fixed_initialize` for `CoriolisBu`.  I am looking into what may have caused it.

**Pull request merged**
