### PR TITLE
+Added the ability to read a time type as a date

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
Added the ability to read a time-type parameter as a date in the format
YYYY-MM-DD HH:MM:SS or Y, M, D, H, M, S.  Also added the ability to specify that
loging of a time-type should also be written as a date (in the first format).
All answers are bitwise identical.

### CODE REVIEW

**Comment by adcroft** [comment]
SEGV in file_parser?  https://gitlab.gfdl.noaa.gov/ogrp/MOM6/builds/4587

```
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               000000000316ACF6  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               000000000316F290  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000002C431F0  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000001DB52FA  mom_file_parser_m        1786  MOM_file_parser.F90
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000001B70939  sis_dyn_trans_mp_        1307  SIS_dyn_trans.F90
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000001B0A74F  ice_model_mod_mp_        2425  ice_model.F90
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               000000000040E628  coupler_main_IP_c        1717  coupler_main.F90
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000000403DA0  MAIN__                    560  coupler_main.F90
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000000400F5E  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               000000000324D971  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.intel: MOM6               0000000000400E39  Unknown               Unknown  Unknown
```

**Comment by adcroft** [comment]
And from Travis:
```
src/framework/MOM_file_parser.F90, line 849: Trailing space detected "  endif "
src/framework/MOM_file_parser.F90, line 1504: Blank line contains spaces
```

**Comment by Hallberg-NOAA** [comment]
Our working hypothesis here is that the SEGV errors were due to the use of libraries and the fact that SIS2 utilizes MOM6 framework code. The pipeline compiler does not always recognize this dependency.

  As for the trailing blanks, someone just got careless...  (This has now been fixed.)

**Comment by adcroft** [comment]
Note to everyone else: you might need to rebuild your SIS2 object files, following Bob's comments.

**Pull request merged**
