### PR TITLE
Changes variable intents for cray compatibility

### PR DESCRIPTION
**Pull request by byrdman1982**
Changes variable intents from intent(in) to intent(inout) to be compatible with the cray compiler.

This has been tested on gaea with the AM4 warsaw_201710 code.

Assigning to @nikizadehgfdl  for testing.

### CODE REVIEW

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/2721

**Comment by Hallberg-NOAA** [comment]
Thank you, @byrdman1982, for these corrections.  Most of these are required because of the addition of halo update calls.

  However, I do not think that the intent of the Time argument on line 673 of MOM_ALE_sponge.F90 should be changed to intent(inout).  This variable is not changed within this subroutine, and the two calls that take this variable as an argument have it appropriately set to intent(in).

  Also, when changing the intents from "intent(in)    ::" to "intent(inout)    ::", please remove 3 of the following spaces, as "intent(inout) ::", so that the vertically aligned formatting of the arguments is retained.

**Comment by adcroft** [comment]
@byrdman1982 Apart from comment above from @Hallberg-NOAA , other tests passed. Are you using an unmodified ncrc-cray.mk template from mkmf? If so, what commit of mkmf are you using? Thx.

**Comment by adcroft** [comment]
- I have made the whitespace fixes suggested by @Hallberg-NOAA.
- I also changed the intent of that Time argument back to intent(in) so that we can proceed with the PR.
   - Testing now in https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/2726
- I briefly tried compiling with the Cray compiler but it got hung up on coupler_types so I have not been able to test that my changes still work for you. @byrdman1982 , can you check that I've not broken your build by reverting the intent for Time?
- In the meantime I'm accepting the modified PR, once it's passed testing again.

**Comment by byrdman1982** [comment]
@adcroft sorry for the delayed response.  I switched time to `intent (in)` and my compile still worked.  Thank you for catching that.  I'm running on gaea using bronx-12.  The cray.mk file is at /ncrc/home2/fms/local/opt/fre-commands/bronx-12/site/ncrc3/cray.mk (this will change to cce.mk soon).  If you are running this using bronx-12, you have to modify the compile script to point to this cray.mk file instead of the default cce.mk file.  There is a fix for this waiting to be merged in to bronx-12.  In the build directory you can run `sed -i -e 's/cce.mk/cray.mk/' compile_*` .
My mkmf is located at /ncrc/home2/fms/local/opt/fre-commands/bronx-12/bin/mkmf.

**Pull request merged**
