### PR TITLE
Adds first version of the MCT driver

### PR DESCRIPTION
**Pull request by gustavo-marques**
**Summary of commits:**

* `config_src/mct_driver/ocn_comp_mct.F90` - Adds the main driver for MOM6 in CIME. This module 1) initializes, 2) runs, and 3) finalizes MOM6 via the CESM framework. The model successfully run for one month using CORE forcing. There are mismatches between MCT and MOM6 in terms of ice ocean boundary fluxes that need to be accounted in the future. These have been documented in the code. We have followed MOM6 code style guide and the module has been Doxygenized.

Changes on existent MOM6 modules

* `config_src/coupled_driver/ocean_model_MOM.F90` - Adds a subroutine that returns pointers to objects within ocean_state_type;

* `src/core/MOM_grid.F90` - Adds a subroutine that returns global shape of horizontal grid;

* `src/framework/MOM_domains.F90` - Adds a subroutine that returns the global shape of h-point arrays;

* `src/initialization/MOM_coord_initialization.F90` - Fixes gprime(1) when no layer coordinates are set. 

* `src/initialization/MOM_state_initialization.F90` - Adds option to read initial temp and salt from separate files;

* `src/ice_shelf/MOM_ice_shelf.F90` - Removes frazil's contribution to evaporation. Frazil formation was being converted to surface layer evaporation under ice shelves and this was double counting the effect of frazil on the system;

* `src/parameterizations/lateral/MOM_hor_visc.F90` - Avoids a SEGV when OBC are not in use with bi-harmonic friction.

### CODE REVIEW

**Comment by adcroft** [comment]
@kshedstrom Can you that check that this branch works for you (given the caveats in previous comment) and give us the thumbs up or down?

**Comment by kshedstrom** [comment]
So I have to guess which version of FMS? It's not obvious to me how to know that. Guessing dev/master gives a compile-time error:

   -fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check -I/u1/uaf/kshedstrom/include  -I../../shared/repro  -c -I//center1/d/kate/ESMG/ESMG-configs/src/MOM6/src/framework	//center1/d/kate/ESMG/ESMG-configs/src/MOM6/src/diagnostics/MOM_debugging.F90
//center1/d/kate/ESMG/ESMG-configs/src/MOM6/src/framework/MOM_io.F90:19:32:

 use fms_io_mod,           only : get_filename_appendix => get_filename_appendix
                                1
Error: Symbol ‘get_filename_appendix’ referenced at (1) not found in module ‘fms_io_mod’
//center1/d/kate/ESMG/ESMG-configs/src/MOM6/src/framework/MOM_io.F90:39:93:

 public :: close_file, create_file, field_exists, field_size, fieldtype, get_filename_appendix
                                                                                             1
Error: Symbol ‘get_filename_appendix’ at (1) has no IMPLICIT type
make[1]: *** [Makefile:175: MOM_io.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/import/c1/w/kshedstrom/MOM6/build/gnu/symmetric_ocean_only/repro'
make: *** [Makefile:497: /center1/w/kshedstrom/MOM6/build/gnu/symmetric_ocean_only/repro/MOM6] Error 2

**Comment by adcroft** [comment]
Sorry, I should have specified:
32a792370d1ee4254b3cf6ab93c769076c5c447c, as recorded in src/ of dev/master
at https://github.com/NOAA-GFDL/MOM6-examples/tree/dev/master/src.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by kshedstrom** [comment]
Thanks. Yes, all my little ocean-only tests run, with small answer changes I would expect. CCS is in the queue.

**Pull request merged**
