### PR TITLE
+REMAP_AUX needs at least one more halo update.

### PR DESCRIPTION
**Pull request by kshedstrom**
- Only when REMAP_AUXILIARY_VARS is true.
 - Addresses #495 
 - There is still a problem with diffu and diffv when REMAP_AUXILIARY_VARS is true. The first call to horizontal_viscosity after the first REMAP returns with a tile boundary mismatch.

### CODE REVIEW

**Review by Hallberg-NOAA — APPROVED** [review]
I agree that these halo updates are necessary and correct.

  As written, there will be two separate points of synchronization for the two pass vector calls.  This could be reduced to a single point of synchronization (and made more efficient) by adding the argument `complete=.false.` on the first call and (optionally) `complete=.true.` on the second, or they could be combined into a group_pass.

**Comment by kshedstrom** [comment]
Thanks for the comments, @Hallberg-NOAA. I will submit a fix. Meanwhile, I will also attempt a fix to the diffu issue, which is due to needing a halo update on r[xy]_normal after the call to remap_OBC_fields.

**Comment by marshallward** [comment]
@kshedstrom Is this ready to go in?  Or did you want to continue working on it?

**Comment by kshedstrom** [comment]
You can merge this now. The Bering domain now behaves, but Mehmet and I are seeing other lingering issues with different processor counts for both the North Atlantic and the Arctic. But I think the REMAP_AUXILIARY_VARS and the OBCs should both be good now.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/20915 :heavy_check_mark:

**Pull request merged**
