### PR TITLE
Dev master candidate from NCAR 2019/10/02

### PR DESCRIPTION
**Pull request by gustavo-marques**
**Summary:**

* Corrects time-related arguments in ocean_model_init in the MCT and NUOPC caps. This fixed the issue of overwriting ocean.stats every time the model was restarted;
* Obsoletes ADD_KV_SLOW and removes visc%Kv_slow from restart files since it is no longer needed;
* Checks for consistency of lat, lon and mask between mesh and mom6 grid in the NUOPC cap;
* Fixes the coding issues with GME described in https://github.com/NCAR/MOM6/issues/109;
* Adds NCAR version of MOM6 Doxygen (https://ncar.github.io/MOM6/APIs/), and improves NUOPC documentation.

**Changes in answers and MOM parameters**

The following parameter will be added in MOM_parameter_doc.all when USE_MEKE = True:

```
MEKE_EQUILIBRIUM_ALT = False    !   [Boolean] default = False
                                ! If true, use an alternative formula for computing the (equilibrium)initial
                                ! value of MEKE.
```

The following will be removed:

```
ADD_KV_SLOW = False             !   [Boolean] default = False
                                ! If true, the background vertical viscosity in the interior (i.e., tidal +
                                ! background + shear + convection) is added when computing the coupling
                                ! coefficient. The purpose of this flag is to be able to recover previous
                                ! answers and it will likely be removed in the future since this option should
                                ! always be true.
```
I could not figure out why the answers change for the following configuration (perhaps compiler version? I've used intel/17.0.1):  

`	modified:   regressions/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel`

All other configurations in MOM6-examples are bit for bit.

### CODE REVIEW

**Comment by gustavo-marques** [comment]
@Hallberg-NOAA, sorry for missing the comments documenting the dimensional rescaling of variables. These have been restored now. Thank you for catching this.

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by marshallward** [comment]
Ignore my last comment, I see from ba2f186 that this was intentional.  (This may require an update of the OpenMP directive, btw).

**Comment by marshallward** [comment]
Github is not reporting any conflicts here, but if I try to do a local merge then I get a conflict in `src/parameterizations/lateral/MOM_hor_visc.F90` at L1379.

@gustavo-marques I'm not really sure the best way to resolve this on our end, but if you wanted to do a dev/gfdl merge into your PR, resolve the conflict, and then update the PR, maybe that would work?

**Comment by adcroft** [comment]
If there is no conflict with dev/master then all is good for this PR. Merging dev/master back into dev/gfdl is our problem. This PR was OK'd already (before we lost the machine) so complete the merge on dev/master and respectively update MOM6-examples and the stats repo. We'll look at merging onto dev/gfdl after that.

**Comment by marshallward** [comment]
Ah right ok, wrong branch.  Sorry about that.  Should we (i.e. you) just go ahead and merge this then?

**Comment by marshallward** [comment]
Right, sorry, wrong branch.  Will deal with this as a `dev/master` merge.

**Pull request merged**
