### PR TITLE
FMS1 Framework integration

### PR DESCRIPTION
**Pull request by marshallward**
This pull request introduces the new `config_src` layout, which includes dedicated directories for the framework infrastructure, couplers, drivers, and memory preprocessing.

Reviewers requested:
* :heavy_check_mark: EMC (@jiandewang)
* :heavy_check_mark: ESMG (@kshedstrom)
* :heavy_check_mark: FSU / HYCOM3 (@abozec / @awallcraft)
* :heavy_check_mark: NASA / GMAO (@sanAkel)
* :heavy_check_mark: NCAR (@alperaltuntas / @gustavo-marques)

**Existing build scripts with explicit paths to `config_src` are unlikely to work after this merge**.  This includes calls to `mkmf` or any compiler flags containing directories.  Please carefully confirm that you are still able to build and run your models with this PR.

The FMS1 implementation is now moved into `config_src/infra/FMS1`, and `src` should no longer contain any explicit calls to FMS.

Couplers and drivers have been renamed and moved into the `drivers` directory.  Many are now denoted with the `_cap` suffix, e.g.
* `coupled_driver` -> `FMS_cap`
* `mct_driver` -> `mct_cap`
* `nuopc_driver` -> `nuopc_cap`

`MOM_memory.h` headers are now moved into the `config_src/memory` directory.

The documentation, build system, and verification tests paths have also been updated to reflect this change.

Also, the `target` build in the testing will now use its own `configure.ac` rather than the current repository.  In particular, the current regression tests can now use the legacy layout, and future directory tree changes will not break the regression tests.

Commits:
- #1341: Hallberg noaa gfdl fms2 (@adcroft)
- #1339: +New config_src directory structure (@Hallberg-NOAA)

Contributors:
  - @adcroft: 1
  - @Hallberg-NOAA: 1

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR. If this is for the whole consortium to evaluate, you should probably add other mentions.

**Comment by marshallward** [comment]
Thanks for the reminder, @kshedstrom.

Could the others please review?

* @alperaltuntas / @gustavo-marques 
* @jiandewang 
* @abozec / @awallcraft 
* @sanAkel

**Comment by jiandewang** [comment]
@marshallward There are some directories naming changings, but there are no files adding/deleting or renaming, is that right ?

**Comment by marshallward** [comment]
@jiandewang Yes, that's correct.  The new files were added in the previous PR to `main`.

**Comment by alperaltuntas** [comment]
I approve this PR.

**Review by abozec — APPROVED** [review]
COAPS approves this PR.

**Comment by jiandewang** [comment]
@marshallward in EMC we are in final stage to merge your previous PR, so please bear me a bit delay on this PR.

**Comment by marshallward** [comment]
@jiandewang No hurry, please take as long as you need.

**Comment by jiandewang** [comment]
> @jiandewang No hurry, please take as long as you need.

@thanks for your understanding

**Review by sanAkel — APPROVED** [review]
This PR can be merged. (No change in answers w.r.t. _present_ version of GEOS coupled model with MOM6.) 

If not already in place, I would also suggest/request an edit to the `compile instructions` at MOM6-examples: [ocean-only](https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#compiling-mom6-in-ocean-only-mode-without-sis2), [ice-ocean](https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#compiling-mom6-in-mom6-sis2-coupled-mode) reflecting the reorganized directory structure.

**Comment by adcroft** [comment]
@sanAkel Thanks. Updated instructions have been written but not posted. Preview is at https://github.com/NOAA-GFDL/MOM6-examples/wiki/Temp---new-Getting-Started

**Comment by jiandewang** [comment]
@marshallward: works fine in UFS.

**Comment by marshallward** [comment]
OK, I will go ahead and merge this PR now.

Modes which need to use the legacy FMS library should be able to continue doing so, and ought not need any other major changes to their build process.

For those who need to upgrade to FMS2, we will start consolidating existing work into the FMS2 adapters and will update `main` as soon as possible.

**Pull request merged**
