### PR TITLE
Added modified Leith viscosity.

### PR DESCRIPTION
**Pull request by septicscuzzy**
Added a term proportional to the gradient of divergence to the
Leith viscosity, which turns regular 2D Leith into Modified Leith.

### CODE REVIEW

**Comment by adcroft** [comment]
@Hallberg-NOAA  FYI, this passes our tests. Just needs you code review. https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/1938

**Comment by septicscuzzy** [comment]
In the land of Mordor, in the fires of Mount Doom, the Dark Lord
Bachman forged in secret, a master closure, to control all others. And into
this closure he poured his cruelty, his malice, and his will to dominate
all ocean modeling.

On Tue, Jun 13, 2017 at 11:24 AM, Alistair Adcroft <notifications@github.com

**Comment by adcroft** [comment]
image

**Comment by Hallberg-NOAA** [comment]
Overall this looks great, but there are two things that need to be fixed here before it should be merged.
First, the new variable CS%Modified_Leith is never initialized, which means that there may be capricious and compiler-dependent behavior to the model.  A get_param call for MODIFIED_LEITH is needed.
Second, the caption in the clever figure that @adcroft  contributed a couple of hours ago needs to be fixed to make it one-message!

**Comment by adcroft** [comment]
It's in the pipe...  https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/2007

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Pull request merged**
