### PR TITLE
Fix for MEKE not reproducing across layouts

### PR DESCRIPTION
**Pull request by adcroft**
This PR should fix the non-reproducing across layout issue reported for OM4_05. I do not think this will address the restart issue (which I have not tested).

This has two bug fixes:
1. An array shape mistake, that only affected symmetric memory mode (b0a0600b).
2. A missing halo-update dependent on a non-zero parameter (bf8a2d1a).

I also added some extra checksums while debugging this.

### CODE REVIEW

**Comment by MJHarrison-GFDL** [comment]
As suspected, this did not fix the restart issue

**Comment by MJHarrison-GFDL** [comment]
Regarding the restart problem, mask2dcv is zero to the left of the first computational row

**Comment by nikizadehgfdl** [comment]
This fixed the layout non-repro for 1/2 degree models. But it does not fix the restart issue.

**Comment by adcroft** [comment]
Some progress is better than none.On May 31, 2017 2:43 PM, Niki Zadeh <notifications@github.com> wrote:This fixed the layout non-repro for 1/2 degree models. But it does not fix the restart issue.

**Comment by MJHarrison-GFDL** [comment]
This has nothing to do with my restart problem, but I'm pretty sure this is incorrect.

https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/parameterizations/lateral/MOM_MEKE.F90#L177

**Pull request merged**
