### PR TITLE
dev-master-candidate-2019-12-17

### PR DESCRIPTION
**Pull request by adcroft**
This is the PR onto dev/master promised on last weeks dev call. The main changes are:
- More test mechanisms added to Travis-CI
- Two new TCs (test configurations)
- Further dimensional consistency of expressions
- Bug fixes:
  - Units of MEKE advection
  - Multiple OBC 
  - Downsampled transport fix
  - OMP directives
  - Multiple diagnostics

The parameter documentation is updated so I've pushed a corresponding branch to MOM6-examples: [dev-master-candidate-2019-12-17](https://github.com/NOAA-GFDL/MOM6-examples/tree/dev-master-candidate-2019-12-17)

The length of the list of PRs is misleading. I suspect almost every file has been touched at some point since the last PR to dev/master. There are 365 commits hidden in here:
#1040 from Hallberg-NOAA/rescale_diag_fix
#1039 from adcroft/fix-units-for-meke-advection
#1037 from Hallberg-NOAA/revise_OBCs
#1031 from marshallward/tc4_fix
#1034 from marshallward/adiabatic_clock_id_fix
#1032 from Hallberg-NOAA/rescale_cleanup
#1030 from marshallward/travis_regression_fix
#1019 from Hallberg-NOAA/density_rescale
#1026 from marshallward/nan_merge
#1023 from marshallward/visc_max_chksums
#1021 from marshallward/variable_init_fixes
#1022 from nikizadehgfdl/fix_downsampled_transport_diags
#1025 from marshallward/dev_merge
#1004 from adcroft/tc-reconfig
#1020 from marshallward/mk_fixes
#1018 from marshallward/ale_ineq_1016
#1014 from marshallward/meke_diag_arrays
#1012 from marshallward/omp_test
#1010 from nikizadehgfdl/fix_openmp_compile
#1011 from marshallward/popcnt
#1009 from marshallward/negzero_minmax_log
#1005 from marshallward/make_parallel
#1003 from adcroft/make-label-output
#1002 from marshallward/diag_scaling_p2
#1000 from MJHarrison-GFDL/ALE_sponges_ongrid
#1001 from adcroft/make-src-dependency
#996 from marshallward/codecov_config
#993 from marshallward/travis_stderr
#994 from wfcooke/user/wfc/ePBL_fix
#991 from marshallward/tendency_scaling
#989 from adcroft/tc-reconfig

If you have conflicts it will most likely be due to the dimensional scaling. If you need assistance resolving a conflict reach out to @Hallberg-NOAA .

As usual we'd like reviews from the leads on the major forks: @jiandewang, @awallcraft, @kshedstrom, @gustavo-marques . The latter two have the ability to use the review button - we're trying to get you others that permission too.

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR, though I do feel left out. It changes answers (ever so slightly) for the dumbbells and the seamounts.

**Comment by adcroft** [comment]
Yes, I felt bad about not handling #1045 before making the PR but when I prepared it last night #1045 had a red X (because Travis-CI failed to launch, not because of the code).

**Comment by jiandewang** [comment]
works fine on NCEP WCOSS machine, testing on HEAR now (may need to wait for 1-2 days as HEAR is unstable today)

**Comment by awallcraft** [comment]
I approve this PR.  Alan.

**Comment by jiandewang** [comment]
works fine on NCEP HERA machine, answer changes, approve this PR.

**Comment by gustavo-marques** [comment]
Mct tests are failing due to an error in mct_driver/mom_ocean_model_mct.F90, see
https://github.com/NCAR/MOM6/pull/136#pullrequestreview-337916773

The equivalent call in [coupled_driver](https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/config_src/coupled_driver/ocean_model_MOM.F90#L510) does not have this extra argument. We will wait for @Hallberg-NOAA's confirmation before deleting it.

**Comment by gustavo-marques** [comment]
We approve this PR.

**Pull request merged**
