### PR TITLE
+Add particle code option to advect with uhtr

### PR DESCRIPTION
**Pull request by cspencerjones**
The particle code has so far used the same velocity has was used in the dynamics step. I would like to add the option for the particle code to use uhtr/h and vhtr/h, so that the velocities used to advect particles may include the effects of parameterized eddies.

To make this work, I have added a flag that controls which velocity to use and moved the particles_run step to take place after uhtr and vhtr are defined. The interfaces in the code and in config_src/external are updated to pass this information to the drifters package.

### CODE REVIEW

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
This is a clever idea for parsimoniously expanding the options for the `particles_run()` code.  Overall, I like where this is going, but given that the `uo` and `vo` arguments to particles run might be either velocities or thickness transports, with different units, I think that the comments describing these arguments also need to be modified accordingly.

**Comment by cspencerjones** [comment]
Thanks for this suggestion @Hallberg-NOAA . I had missed this, and I have made an update. Are the units ok like this? I looked at some other MOM6 code and it seemed like this style would be ok, but I'm happy to change it.

**Review by Hallberg-NOAA — APPROVED** [review]

**Review by Hallberg-NOAA — COMMENTED** [review]
There are still a couple of typos (e.g., "us_uh" instead of "use_uh") in the comments, but the documentation of the units with the various options is correct now.

**Comment by cspencerjones** [comment]
Thanks! I fixed the typos you pointed out, so we should be good to go.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/20908 :heavy_check_mark:

**Pull request merged**
