### PR TITLE
Fix a rescaling bug with MEKE_EQUILIBRIUM_ALT

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
Corrected a bug in a dimensional rescaling factor that will cause test cases
using MEKE with MEKE_EQUILIBRIUM_ALT = True to fail dimensional consistency
testing.  However, answers are unchanged when no rescaling is used.  This minor
bug has been in the code since the MEKE_EQUILIBRIUM_ALT was first introduced in
2019.  All answers in the existing MOM6-examples test suite are bitwise
identical.

### CODE REVIEW

**Comment by klindsay28** [comment]
Curiously, this was previously fixed in https://github.com/mom-ocean/MOM6/pull/1491
At some point, which I haven't been able to figure out when, it got re-broken.
It has been refixed on the NCAR fork with https://github.com/NCAR/MOM6/pull/209

**Review by gustavo-marques — APPROVED** [review]

**Review by adcroft — APPROVED** [review]
Passed: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/15663

**Comment by marshallward** [comment]
> Curiously, this was previously fixed in [mom-ocean#1491](https://github.com/mom-ocean/MOM6/pull/1491) At some point, which I haven't been able to figure out when, it got re-broken. It has been refixed on the NCAR fork with [NCAR#209](https://github.com/NCAR/MOM6/pull/209)

The commit appears in the history: [9011801b617ef6c09a2e48f8685532886122d10f](https://github.com/mom-ocean/MOM6/commit/9011801b617ef6c09a2e48f8685532886122d10f)

And yet the file reports that the scaling factor has been unchanged for years: https://github.com/mom-ocean/MOM6/blame/main/src/parameterizations/lateral/MOM_MEKE.F90

All a bit worrying.  Maybe I failed to merge maih to dev/gfdl?  That would be monumentally dumb, but I do recall some drama around it.

**Comment by marshallward** [comment]
I spot checked other diffs from this PR contribution (other dimensional MEKE fixes, CFC code, etc), and as far as I can tell everything else is in there.  So odd...

**Comment by klindsay28** [comment]
A possibility is that the change was lost during by-hand conflict resolution during a merge. My mod changed `US%Z_to_m*G%bathyT` to `US%Z_to_L*G%bathyT`. On another branch, commit `8a0ae944d181ec6d109a029568f27eb23d55e46f` changed this expression to `US%Z_to_m*depth_tot`. Merging these, wherever it occurred, would have led to conflict requiring resolution. Perhaps the latter version was selected during conflict resolution, instead of combining them to obtain `US%Z_to_L*depth_tot`. The reversion was flagged in the NCAR/CESM test suite, because we use `MEKE_equilibrium_alt == .true.`, so I don't think the reversion occurred here.

I suspect it was during a main->dev/gfdl merge. Testing of that merge must have missed this omission, I suspect because it didn't cover `MEKE_equilibrium_alt == .true.`. Because of the combinatorial explosion of options, it's unrealistic to expect every combination of options to be tested, so this is not surprising. However, I think it does highlight the risk of modifying code not covered by one's test suite.

**Comment by marshallward** [comment]
That sounds plausible.  I don't see any other missing changes, and a hand-merge would be the place for a small error to appear.  I was more worried about a total loss of the content, but that doesn't seem to have happened.

I guess we'll just have to be more careful.  (Or develop better unit tests!)

**Comment by adcroft** [comment]
The original fix is in the history but very next commit that changed MEKE.F90 removed it.

. d9af347 2021-09-17 09:43:34 -0400 Use allocate with source to initialize arrays
.   72aabe5 2021-09-14 16:02:24 -0400 Merge branch 'dev/gfdl' into main_to_dev_gfdl
|\  
| *   f44b9c4 2021-09-09 19:09:54 -0400 Merge branch 'dev/gfdl' into offset_bathyT_by_Z_ref
| |\  
| | *   2925661 2021-08-31 15:44:52 -0400 Merge branch 'dev/gfdl' into cpt2gfdl_080622
| | |\  
| | * | ba6f56d 2021-08-30 13:33:50 -0600 Add code that was deleted unintentionally
| | * |   53443ae 2021-08-30 11:27:26 -0600 Merge branch 'meke_damping' into cpt2gfdl_080622
| | |\ \  
| | | * | 868c11a 2021-08-30 10:40:58 -0600 Always initialize drag_rate
| | * | | e28f74d 2021-08-05 15:24:57 -0600 Merge branch 'dev/gfdl' into dev/cpt
| | |/ /  
| | * | 156d02c 2021-08-04 16:26:24 -0600 Make use_drag_rate independent of MEKE_damping
| | * | 27cd2ed 2021-02-22 09:15:56 -0500 Merge pull request #6 from NOAA-GFDL/dev-gfdl-main-candidate-2021-02-19
| |  /  
| * | 060c412 2021-08-31 09:24:34 -0400 (*)Offset G%bathyT by -G%Z_ref
| |/  
| * 6979c29 2021-08-26 21:36:49 -0400 +(*)Add option for MEKE to calculate total depth
| * 3150c9f 2021-08-17 17:39:01 -0400 Merge branch 'Z_ref_prelude' into Z_ref_prep2
. 9011801 2021-08-23 09:31:03 -0600 Various dimension rescaling fixes
. 3117b98 2021-08-02 13:50:09 -0600 merge dev/ncar with main 210723


203a19f Fix a rescaling bug with MEKE_EQUILIBRIUM_ALT
48ae48a Remove unused variables
7c3f31b +(*)Write unscaled MOM6 restart files
d8abf05 Merge branch 'dev/gfdl' into more_unit_fixes
4e6e73f Merge branch 'dev/gfdl' into initialized_tests
be50361 Add initialization tests using CS%initialized
4e67533 Corrected the descriptions of 60 variables
7a63130 MOM_restart_cs pointer removal
65a3516 MEKE_type pointer removal
0e19103 MEKE pointer cleanup
e2e5787 Corrected the units of 124 variables
43d4f16 (+*)Fix MEKE advection bug
d9af347 Use allocate with source to initialize arrays
72aabe5 Merge branch 'dev/gfdl' into main_to_dev_gfdl
f44b9c4 Merge branch 'dev/gfdl' into offset_bathyT_by_Z_ref
2925661 Merge branch 'dev/gfdl' into cpt2gfdl_080622
ba6f56d Add code that was deleted unintentionally
53443ae Merge branch 'meke_damping' into cpt2gfdl_080622
868c11a Always initialize drag_rate
e28f74d Merge branch 'dev/gfdl' into dev/cpt
156d02c Make use_drag_rate independent of MEKE_damping
060c412 (*)Offset G%bathyT by -G%Z_ref
6979c29 +(*)Add option for MEKE to calculate total depth
8a0ae94 +Pass depth_tot around within MOM_MEKE
c72d441 (*)Fix dimensionally inconsistent MEKE beta calcs
9011801 Various dimension rescaling fixes



Aug 23: https://github.com/NOAA-GFDL/MOM6/blob/9011801b617ef6c09a2e48f8685532886122d10f/src/parameterizations/lateral/MOM_MEKE.F90#L699
Aug 26: https://github.com/NOAA-GFDL/MOM6/blob/6979c298419a3a724edacfda506f378a6fab96f1/src/parameterizations/lateral/MOM_MEKE.F90#L712

**Comment by adcroft** [comment]
I accidentally replied while still editing - deleted and re-sent. This issue was indeed caused by a bad conflict resolution.

The GH history for MOM_MEKE.F90, https://github.com/NOAA-GFDL/MOM6/commits/dev/gfdl/src/parameterizations/lateral/MOM_MEKE.F90, shows things chronologically. 
This makes it seem that the correction on Aug 23 by @klindsay28, https://github.com/NOAA-GFDL/MOM6/blob/9011801b617ef6c09a2e48f8685532886122d10f/src/parameterizations/lateral/MOM_MEKE.F90#L699,  was undone in the very next commit on Aug 26, https://github.com/NOAA-GFDL/MOM6/blob/6979c298419a3a724edacfda506f378a6fab96f1/src/parameterizations/lateral/MOM_MEKE.F90#L712 .

It turns out none of the commits in a line between 9011801..6979c29 are not at fault
```
$ git log --format="format:%h %ad %s" --date=short 9011801..6979c29 src/parameterizations/lateral/MOM_MEKE.F90
```
6979c29 2021-08-26 +(*)Add option for MEKE to calculate total depth
8a0ae94 2021-08-17 +Pass depth_tot around within MOM_MEKE
c72d441 2021-08-15 (*)Fix dimensionally inconsistent MEKE beta calcs

That's because this relevant line was being edited on several branches at once:
image

Above you can see that  8a0ae94 changed `G%bathyT` to `depth_tot` on the same line which has corrected the scaling that was already on the dev/gfdl from NCAR. When conflict resolving in the merge between the two branches, https://github.com/NOAA-GFDL/MOM6/commit/72aabe5a4f225d3a3ba978077d6a01b8bc4def6a#diff-2bf6c52474ad3142c4902b0f94ed67365c19e0bc7a6a61c4dcbc4e453330d258R712, neither option was correct without editing: either the `depth_tot` version needed the correct scaling applied or the correct scaling needed the change in variable. I think one was selected and the critical single character was missed.

**Pull request merged**
