### PR TITLE
Inline harmonic analysis

### PR DESCRIPTION
**Pull request by c2xu**
The module MOM_harmonic_analysis computes the constant coefficients of sine/cosine functions for the SSH and barotropic velocity fields of each tidal constituent.

### CODE REVIEW

**Comment by c2xu** [comment]
@Hallberg-NOAA There was some issue with rebase in my previous attempt, so I closed that PR and created this new one.

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
This PR is a revised version of the previous PR #603 that already underwent extensive reviews.  Although the issues with reproducing across restarts when the analysis period spans a restart have not been addressed yet, everything else is looking good to me.

  There are a couple of minor issues that I think should be considered before this PR is finally accepted:
1. Please reconsider the use of `l` for a loop index in `HA_solver()` because `1` and `l` can be tough to distinguish, whereas `m` and `1` are clearly different.
2. Please avoid the use of the F90 `dot_product()` function which uses sums in an indeterminate order and therefore can give answers with real arguments that depend on compiler version and implementation details. (This is the same as the problem with the F90 `sum()` function; the use of both `sum()` and `dot_product()` are discouraged in MOM6.)  The math is correct here, but by doing these real sums with explicit loops, the answers should become reproducible across compilers and levels of optimization.
3. Rather than repeatedly dividing by the same `FtFw(k,k)` diagonal elements in lines 387, 397 and 404 of `HA_solver()`, consider taking the reciprocal of the diagonal and the multiplying by this reciprocal.  This is an optimization that compilers would usually do at a certain optimization level, but not when debugging, and this leads to slight changes in answers.  Explicitly doing this optimization ourselves means that we are more likely to get the same answers across different levels of optimization, which can make it easier to debug any problems that arise.

**Comment by c2xu** [comment]
> This PR is a revised version of the previous PR #603 that already underwent extensive reviews. Although the issues with reproducing across restarts when the analysis period spans a restart have not been addressed yet, everything else is looking good to me.
> 
> There are a couple of minor issues that I think should be considered before this PR is finally accepted:
> 
> 1. Please reconsider the use of `l` for a loop index in `HA_solver()` because `1` and `l` can be tough to distinguish, whereas `m` and `1` are clearly different.
> 2. Please avoid the use of the F90 `dot_product()` function which uses sums in an indeterminate order and therefore can give answers with real arguments that depend on compiler version and implementation details. (This is the same as the problem with the F90 `sum()` function; the use of both `sum()` and `dot_product()` are discouraged in MOM6.)  The math is correct here, but by doing these real sums with explicit loops, the answers should become reproducible across compilers and levels of optimization.
> 3. Rather than repeatedly dividing by the same `FtFw(k,k)` diagonal elements in lines 387, 397 and 404 of `HA_solver()`, consider taking the reciprocal of the diagonal and the multiplying by this reciprocal.  This is an optimization that compilers would usually do at a certain optimization level, but not when debugging, and this leads to slight changes in answers.  Explicitly doing this optimization ourselves means that we are more likely to get the same answers across different levels of optimization, which can make it easier to debug any problems that arise.

The new commit optimized the performance of `HA_solver` as requested.

**Review by Hallberg-NOAA — APPROVED** [review]
Thank you very much for this contribution, and for making the suggested revisions.  I am very happy to approve this excellent contribution of important new diagnostic capabilities to MOM6.

**Comment by Hallberg-NOAA** [comment]
This PR has passed the pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/24185 with the expected warnings about new runtime parameters in cases that have tides enabled.

**Pull request merged**
