### PR TITLE
dev/gfdl main candidate 2021-03-26

### PR DESCRIPTION
**Pull request by marshallward**
This PR is a minor update to the `main` branch, unrelated to the FMS2 update.  This is a joint update from GFDL and EMC.

Review request:
* :heavy_check_mark: COAPS  / FSU: @abozec / @awallcraft
* :heavy_check_mark: EMC: @jiandewang
* :heavy_check_mark: ESMG: @kshedstrom
* :heavy_check_mark: NASA-GMAO: @sanAkel
* :heavy_check_mark: NCAR: @alperaltuntas / @gustavo-marques

The main purpose of this PR is to restore the history between `main`, `dev/gfdl`, and `dev/emc`.  This was caused (by myself) when `main` was accidentally updated with content from `dev/gfdl` during the `main` -> `dev/gfdl` update.

Although we reversed the accidental update to `main`, the timing was such that the new content ended up in `dev/emc` before the reversal.

To resolve this, we locally merged `dev/emc` into `dev/gfdl`.  The `dev/emc` -> `dev/gfdl` merge contained both our own content as well as new content from `dev/emc`.

Although the number of changes is less than usual, there is at least one answer-changing modification to the NUOPC coupler (flux sign bugfix), as well as another potentially detected by NCAR.

----

GFDL summary:

- #1355: Testing: Recurse target submodules, LDFLAGS hook (@marshallward)
- #1351: Change units of slope returned from calc_isoneutral_slopes() to "Z L-1" (@adcroft)
- #1350: Explicitly set (1x1) io_domain as a default (@Hallberg-NOAA)
- #1349: Merge from main (@marshallward)
- #1348: Bugfix: empty restart_input_dir for *_solo.res (@herrwang0)
- #1346: Bugfix: FGNV streamfunction vertical bounds (@marshallward)
- #1345: Typo correction (@hmkhatri)
- #1344: Update CVMix submodule (@adcroft)
- #1343: Depth-integrated momentum budget diagnostics (@hmkhatri)
- #1340: Fix a missing line regarding vel_underflow (@herrwang0)
- #1338: dynamic ice shelf (@OlgaSergienko)
- #1329: Fix the bug that Rayleigh_[uv] was not initialized in MOM_barotropic (@herrwang0)

Contributors:
  - @marshallward: 3
  - @herrwang0: 3
  - @adcroft: 2
  - @hmkhatri: 2
  - @Hallberg-NOAA: 1
  - @OlgaSergienko: 1

---

EMC summary:

* fixed missing halo in two halo updates for taux and tauy in mom_surface_forcing_nuopc.F90 in nuopc_cap
* allow MOM6 to use a mesh optionally in nuopc_cap
* fixed sign error on fprec passed to ocean in mom_surface_forcing_nuopc.F90 in nuopc_cap (from NCAR)
* allow ocean->land topo edits in MOM_shared_initialization.F90

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR.

**Review by sanAkel — APPROVED** [review]
@marshallward Thanks for requesting to review. 

Thanks to @mathomp4, we are on about a bi-weekly sync schedule with `dev/gfdl`. So [comparing with what we use in GEOS-ESM](https://github.com/GEOS-ESM/MOM6/compare/dev/gfdl...NOAA-GFDL:dev-gfdl-main-candidate-2021-03-26)  the only **relevant** change is a parameter addition of: `ALLOW_LANDMASK_CHANGES`, which is okay!
(Please note that we use  `FMS_cap` driver.)

**Comment by jiandewang** [comment]
approval

**Comment by abozec** [comment]
FSU/COAPS approves too

**Comment by alperaltuntas** [comment]
@jiandewang, @DeniseWorthen, The newly added code block in `config_src/drivers/nuopc_cap/mom_cap.F90` impacts CESM's nuopc configuration. Specifically, this PR changes our geomtype from `ESMF_GEOMTYPE_MESH` to `ESMF_GEOMTYPE_GRID`. Did you intend to change geomptype for CESM configurations as well? If so, could you remind us the rationale? Also mentioning @mvertens.

**Comment by DeniseWorthen** [comment]
@alperaltuntas This was not intended to change CESM configuration. The only intent was to allow UFS to optionally use the mesh instead of the current grid. I realized only later that by setting the config variable false by default this would possibly impact CESM.

**Comment by alperaltuntas** [comment]
Thanks, @DeniseWorthen! We'll wait for you to address this and we will then test the PR again. (No rush on our side.)

**Comment by DeniseWorthen** [comment]
@alperaltuntas Does switching the default value for use_mommesh to ``true`` work for CESM? I've tested it in ufs and it will work on our end. We will eventually switch our default to using the mesh for the mom_cap. 

```
diff --git a/config_src/drivers/nuopc_cap/mom_cap.F90 b/config_src/drivers/nuopc_cap/mom_cap.F90
index c96c98cdd..7dc95e13f 100644
--- a/config_src/drivers/nuopc_cap/mom_cap.F90
+++ b/config_src/drivers/nuopc_cap/mom_cap.F90
@@ -136,7 +136,7 @@ integer              :: logunit  !< stdout logging unit number
 logical              :: profile_memory = .true.
 logical              :: grid_attach_area = .false.
 logical              :: use_coldstart = .true.
-logical              :: use_mommesh = .false.
+logical              :: use_mommesh = .true.
 character(len=128)   :: scalar_field_name = ''
 integer              :: scalar_field_count = 0
 integer              :: scalar_field_idx_grid_nx = 0
@@ -349,7 +349,7 @@ subroutine InitializeP0(gcomp, importState, exportState, clock, rc)
   write(logmsg,*) use_coldstart
   call ESMF_LogWrite('MOM_cap:use_coldstart = '//trim(logmsg), ESMF_LOGMSG_INFO)

-  use_mommesh = .false.
+  use_mommesh = .true.
   call NUOPC_CompAttributeGet(gcomp, name="use_mommesh", value=value, &
        isPresent=isPresent, isSet=isSet, rc=rc)
   if (ChkErr(rc,__LINE__,u_FILE_u)) return
```

**Comment by alperaltuntas** [comment]
@DeniseWorthen, yes, setting `use_mommesh` to true by default works for CESM.

**Comment by marshallward** [comment]
Thank you @DeniseWorthen we'll also merge the work into this PR when it's ready.

**Comment by jiandewang** [comment]
@marshallward I just merged dev-gfdl-main-candidate-2021-03-26 branch to the original branch I provided to you (https://github.com/jiandewang/MOM6/tree/feature/for-GFDL-hot-fixing-20210322), and committed the changing of default value as True for use_mommesh in nuopc_cap/mom_cap.F90.
thanks for the fixing @DeniseWorthen @alperaltuntas

**Comment by marshallward** [comment]
Thanks @jiandewang this branch has now been updated.

Since this change is very minor and isolated to the NUOPC cap, I'll merge this after NCAR approval.

**Comment by alperaltuntas** [comment]
I approve.

**Comment by marshallward** [comment]
Thanks all, merging this now.  Histories between EMC and GFDL (and hopefully everyone else) should now be in sync.

**Pull request merged**
