### PR TITLE
Fix register_diag_field axes_grp pointer init

### PR DESCRIPTION
**Pull request by marshallward**
Several axes_grp pointers in register_diag_field were null()-initialized
at declaration, e.g.
```
  type(axes_grp), pointer :: axes => null()
```
This implicitly declares the pointers with `save`, which preserves its
value across calls.   These axes will not be initialized to null()
(excepting the first call).

In this instance, this was causing d2 axes to be created when they
should not have existed.

This patch eliminates the implicit `save` attributes and applies
explicit initialization when required.

### CODE REVIEW

**Comment by marshallward** [comment]
This should fix #1455.

**Review by Hallberg-NOAA — APPROVED** [review]
I understand and agree with these changes. Moreover, I have verified that the three pointers that are no longer being nullified when they are declared and are not being explicitly nullified in the code are being properly set before they have used.

This PR has passed the TC testing, and I will merge it in as soon as the pipeline tests have run successfully.

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/jobs/67881 passed with doc string msgs

**Comment by marshallward** [comment]
Sorry, I updated main -> dev/gfdl before this managed to get in.

Since the PR has already been approved and tested, I will do this merge and update the parameters.

**Pull request merged**
