### PR TITLE
Dev master candidate 2018 02 06

### PR DESCRIPTION
**Pull request by adcroft**
This is the promised and overdue PR from dev/gfdl onto dev/master (245 commits). There are corresponding branches in MOM6-examples and Gaea-stats so NCAR can see what we changed (since they can currently get the same answers as us).

@gustavo-marques , @kshedstrom , (@awallcraft?)  please evaluate. We'll only accept the PR if there are no conflicts/problems on respective systems.

@nicjhan We should think about exercising the NCI tests on PRs onto dev/master since dev/master is meant to as healthy as possible.

### CODE REVIEW

**Comment by kshedstrom** [comment]
It looks good so far - CCS is still running, everything else is fine. I was surprised that "Obsoleting EXTEND_OBC_SEGMENTS" didn't make it in. Is that true? I know we didn't talk about it.

**Comment by adcroft** [comment]
`EXTEND_OBC_SEGMENTS` has been obsoleted in this PR:
```
> fgrep -r EXTEND_OBC_SEGMENTS src/
src/diagnostics/MOM_obsolete_params.F90:  call obsolete_char(param_file, "EXTEND_OBC_SEGMENTS", &
```

On dev/gfdl it was incorporated [here](https://github.com/NOAA-GFDL/MOM6/blame/dev/gfdl/src/diagnostics/MOM_obsolete_params.F90#L69).

**Comment by kshedstrom** [comment]
Sorry, was just confused by this:

Submodule src/MOM6 5574862b7...4d35928d4:
  > Merge pull request #707 from adcroft/fix-nan-in-radiation-obc
  > Merge branch 'Hallberg-NOAA-restructure_MOM_CS' into dev/gfdl
  > Merge branch 'byrdman1982-user/ter/lineContFix' into dev/gfdl
  > Merge branch 'dev/master' into dev/gfdl
  > Initialize neutral_diffusion_CS%debug to .false.
  > Merge branch 'ashao-collapse_vertmap_ndiff_diags' into dev/gfdl
  > Merge branch 'ashao-collapse_vertmap_ndiff_diags' into dev/gfdl
  < Merge remote-tracking branch 'gfdl/dev/gfdl' into dev/esmg
  < Merge remote-tracking branch 'gfdl/dev/gfdl' into dev/esmg
  < Obsoleting EXTEND_OBC_SEGMENTS.

**Comment by gustavo-marques** [comment]
I've tested CESM/MOM6 by merging dev-master-candidate-2018-02-06 into dev/ncar. I was able to get **identical answers** for the [T62_g16](https://github.com/NCAR/MOM6-cases/blob/dev/cesm/cesm/T62_g16/ocean.stats.intel) test case. 

However, the following three experiments in MOM-examples are failing (after a clean build and using MOM6 dev-master-candidate-2018-02-06 ):

1) MOM6-examples/ice_ocean_SIS2/Baltic_OM4_05/ocean.stats.intel: FATAL from PE     0: grid_mod/get_grid_version: Can't determine the version of the grid spec: none of "x_T", "geolon_t", or "ocn_mosaic_file" exist in file "INPUT/grid_spec.nc"

2) MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: FATAL from PE     1: coupler_init: atmos_npes+ocean_npes must equal npes for concurrent coupling.

3) MOM6-examples/ice_ocean_SIS2/Baltic_OM4_025/ocean.stats.intel: FATAL from PE     0: grid_mod/get_grid_version: Can't determine the version of the grid spec: none of "x_T", "geolon_t", or "ocn_mosaic_file" exist in file "INPUT/grid_spec.nc"

I am using MOM-examples branch dev-master-candidate-2018-02-06, and all sub-modules in MOM-examples/src are consistent with those in that branch, including icebergs at head 8f2203a. 

Any suggestions?

**Comment by kshedstrom** [comment]
By the way, CCS1 passes the test as well, so all is good from ESMG.

**Comment by gustavo-marques** [comment]
I need to get the datasets for the Baltic_OM4_05 and Baltic_OM4_025 test cases. They will solve errors 1 and 3.

**Comment by ashao** [comment]
I uploaded them to the GFDL FTP server: ftp://ftp.gfdl.noaa.gov/pub/Andrew.Shao/Baltic_inputs.tgz

**Comment by gustavo-marques** [comment]
Thanks @ashao!

**Comment by gustavo-marques** [comment]
It now passes the Baltic_OM4_* cases. Still failing for CM2G63L:

MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: FATAL from PE    29: coupler_init: atmos_npes+ocean_npes must equal npes for concurrent coupling.

**Comment by adcroft** [comment]
I recognize the error from when @Hallberg-NOAA did stuff in the coupler but no memory of what it is about. Can you check that:
- input.nml in CM2G63L is setup to use 90 PEs and this is what it says in manifest.mk
- coupler is on commit NOAA-GFDL/coupler@530e9a1
- SIS2 is on commit NOAA-GFDL/SIS2@17245e81b

**Comment by adcroft** [comment]
(Clean build of SIS2 and coupler?)

**Comment by gustavo-marques** [comment]
input.nml in CM2G63L is setup to use 90 PEs:
```
atmos_npes = 30,
ocean_npes = 60,
```
Manifest.mk is wrong:

```
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/01.ignore/ocean.stats.%: NPES=30
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/12.ignore/ocean.stats.%: NPES=30
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/02.ignore/ocean.stats.%: NPES=30
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.%: STATIC_NPES=60
```

Coupler and SIS2 are pointing to the right commit.

Will generate a new Manifest.mk and try again. Thanks @adcroft

**Comment by gustavo-marques** [comment]
All tests passed now.  Answers are identical to those in Gaea-stats. I approve this PR.

**Pull request merged**
