### PR TITLE
dev/master candidate 2019-08-30

### PR DESCRIPTION
**Pull request by adcroft**
This PR submits everything on dev/gfdl as of 2019/08-30 to dev/master. As per usual feedback from @gustavo-marques, @awallcraft, @kshedstrom and @jiandewang is asked for before we accept this PR.

Main features:
- **.testing**: Unbeknownst to most of you, the tests run on Travis-CI have been managed by the contents of the .testing directory for a while. We have now removed the inverse dependency on MOM6-examples and have defined some rudimentary test configurations (TCs) within the .testing. These are not usable configurations for science but sufficient for some code tests. If you have connected Travis-CI to your GitHub fork then with each push you will now invoke tests for 1) restarts, 2) decomposition, 3) dimension scaling, 4) symmetric/non-symmetric memory, 5) uninitialized data, and 6) optimization tolerance. A pull request also conducts a regression test against the parent branch. If Travis-CI is showing you a red X then you can now run the tests interactively. See the .testing/README.md for pointers. @marshallward has made all this work and will be expanding the coverage of these tests on the dev/gfdl branch over the coming months.
- **Dimensional scaling**: @Hallberg-NOAA has touched a lot of code to test that expressions are dimensionally consistent and to allow us to continue to test expressions (this is the reason for the number of commits in this PR).
- **OBC fixes**: @kshedstrom and @MJHarrison-GFDL have been fixing bugs in the open boundary code that does not affect most configurations but since the code is beginning to be used in regional configurations beware.
- **Answer changes**: Numerous fixes have been implemented in diagnostics and forward code. Where the latter changed answers, we made the changes run-time conditional which has introduced numerous flags. By default, all these flags are set to *not* change answer but subsequent to this PR we will be rolling forward all the GFDL configurations to give new (corrected) answers. We recommend evaluating each of the new flags to see if you can move to the newer code so that in the future when we eventually remove the old code you are not adversely affected. The flags are:
  - EPBL_2018_ANSWERS
  - HOR_VISC_2018_ANSWERS
  - OPTICS_2018_ANSWERS
  - SET_DIFF_2018_ANSWERS
  - SET_VISC_2018_ANSWERS
  - SURFACE_FORCING_2018_ANSWERS
  - TIDAL_MIXING_2018_ANSWERS
  - WIND_GYRES_2018_ANSWERS

There are no answer changes implied for the MOM6-examples configurations but because of new parameters a branch with the same name has been pushed to https://github.com/NOAA-GFDL/MOM6-examples/tree/dev-master-candidate-2019-08-30.

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by gustavo-marques** [comment]
We approve this PR.

**Comment by awallcraft** [comment]
I approve this PR.

**Comment by jiandewang** [comment]
Works fine in EMC side, approve this PR.

**Pull request merged**
