### PR TITLE
Rescale ice shelf temperatures

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
Applied dimensional rescaling of all of the ice shelf temperature and salinity
variables that could be modified without requiring any changes at the driver
level.  There is a new unit_scale_type argument to MOM_IS_diag_mediator_init,
mirroring what is done in MOM_diag_mediator_init.  This commit also includes
changing the initial values in the stencil array from -1 to 0, but this
initialization appears to be unnecessary.  A large number of comments were
added, corrected, or modified.  All answers in the test cases are bitwise
identical.

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
Olga Sergienko will be providing a review of this PR after she gets back from the EGU meeting. If she has not done this yet, this PR can be temporarily bypassed.

**Comment by OlgaSergienko** [comment]
The made changes are necessary and the code runs as intended.

**Review by OlgaSergienko — APPROVED** [review]
All made changes are necessary, the code runs as intended.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/15714 :heavy_check_mark:

**Review by marshallward — APPROVED** [review]
Approved on behalf of @OlgaSergienko

**Pull request merged**
