### PR TITLE
Post tracer concentration when synced

### PR DESCRIPTION
**Pull request by ashao**
Tracer concentrations were being posted at the same time as the
transport diagnostics. This leads to some unexpected behavior (e.g. SST
and 3D temperature are not consistent) because the concentrations are
potentially being posted at an intermediate state.

In addition to fixing this problem for all tracers, the subroutine has
been renamed to be more descriptive of what kinds of diagnostics might
fall into this category.

Proposed solution for  https://github.com/NOAA-GFDL/MOM6/issues/1206

### CODE REVIEW

**Comment by ashao** [comment]
@Hallberg-NOAA is too fast for me. I was literally pushing when you made your edit. Now the MOM6 repository will never have the following comment:
> Neglected subroutine in new declaration    
    Careless me left out 'subroutine' in the declaration of
    post_tracer_diagnostics_at_sync

**Comment by Hallberg-NOAA** [comment]
The pipeline testing for this PR is at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11165 .

**Comment by ashao** [comment]
I'll post images of the diagnostics over the weekend.

**Comment by Hallberg-NOAA** [comment]
The updated version of this PR is being tested with https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11170.

**Review by Hallberg-NOAA — APPROVED** [review]
I agree that these are the right changes to address issue #1206, and that the new diagnostic to allow the state of tracers just after advection and horizontal diffusion will help in gracefully transitioning diagnostics for existing experiments.  I am therefore approving this PR.

  However, I do not agree with the change to the name of the subroutine post_tracer_diagnostics to post_tracer_diagnostics_at_sync, and I will be putting in a follow up pull request to revert this to its previous name.  This should be the primary routine for diagnostics of the state of tracers, and I think that the newly extended subroutine name just makes this key point confusing, as was discussed in a call concerning this PR.

**Pull request merged**
