### PR TITLE
Revise framework

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
MOM6: +Revise framework code

  Restructured and revised code in the MOM6 framework directory to separate
MOM6-specific code from modules with direct calls to FMS or mpp routines.  All
answers and output files are bitwise identical, except for the ocean_geometry.F90 file
where incorrect dimensional rescaling of areas was corrected.  Although there are
new interfaces and new optional arguments, and this PR includes changes that
exercise these changes, the contents of the new framework directory can be
swapped with previous versions of the code to give identical answers and all
output files.

  The commits in this PR include:

- NOAA-GFDL/MOM6@45d29a99c +Added an explicit interface to open_file
- NOAA-GFDL/MOM6@51720fb33 +Split MOM_io_wrapper.F90 out from MOM_io.F90
- NOAA-GFDL/MOM6@37ef28bc0 +Add get_domain_components to MOM_domains.F90
- NOAA-GFDL/MOM6@81a6ff8ee +Add explicit interface for field_exists to MOM_io
- NOAA-GFDL/MOM6@d8806f48e +Rename rotated_mpp_chksum to rotated_field_chksum
- NOAA-GFDL/MOM6@adb8ec46b +Add deallocate_MOM_domain and get_layout_extents
- NOAA-GFDL/MOM6@502eb301e (*)Call MOM_write_field in write_ocean_geometry_file
- NOAA-GFDL/MOM6@7091a09c1 +Add MOM_write_field
- NOAA-GFDL/MOM6@ee7dd32c8 +Add create_MOM_domain and MOM_domain_init.F90

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
Pipeline testing for this PR can be found at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11841 .

**Comment by marshallward** [comment]
The pipeline is failing on a segmentation fault:
```
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
```
This fail is happening under the OM4_025 test using the GNU REPRO build.

The GNU Debug build appears to pass for me.

Unfortunately our repro build seems to have been built without -g, so I'm unable to probe very far here, but what I can see appears to be related to a memory allocation:

I will keep looking into this but feel free to do your own inspection, @Hallberg-NOAA.

**Comment by adcroft** [comment]
I see fails over more experiments with both gnu and intel:
```
	modified:   regressions/ice_ocean_SIS2/Baltic_ALE_z_offline_tracers/seaice.stats.intel
	modified:   regressions/ice_ocean_SIS2/Baltic_OM4_025/seaice.stats.intel
	modified:   regressions/ice_ocean_SIS2/OM4_05/seaice.stats.gnu
	modified:   regressions/ice_ocean_SIS2/OM4_05/seaice.stats.intel
	modified:   regressions/ice_ocean_SIS2/OM_1deg/seaice.stats.gnu
	modified:   regressions/ice_ocean_SIS2/OM_1deg/seaice.stats.intel
	modified:   regressions/ice_ocean_SIS2/SIS2/ocean.stats.gnu
	modified:   regressions/ice_ocean_SIS2/SIS2/seaice.stats.gnu
	modified:   regressions/ice_ocean_SIS2/SIS2/seaice.stats.intel
	modified:   regressions/ice_ocean_SIS2/SIS2_bergs_cgrid/seaice.stats.gnu
	modified:   regressions/ice_ocean_SIS2/SIS2_bergs_cgrid/seaice.stats.intel
	modified:   regressions/ice_ocean_SIS2/SIS2_cgrid/ocean.stats.gnu
	modified:   regressions/ice_ocean_SIS2/SIS2_cgrid/seaice.stats.gnu
	modified:   regressions/ice_ocean_SIS2/SIS2_cgrid/seaice.stats.intel
```

**Comment by marshallward** [comment]
Here is a backtrace of the error:
```
#0  0x16698df in ???
	at /home/abuild/rpmbuild/BUILD/glibc-2.26/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
#1  0xdc2eb6 in __mom_domains_MOD_clone_md_to_md
	at /lustre/f2/dev/gfdl/Marshall.Ward/CI/Gaea-stats-MOM6-examples/MOM6-examples/src/MOM6/src/framework/MOM_domains.F90:1802
#2  0xd7813e in __ice_model_mod_MOD_ice_model_init
	at /lustre/f2/dev/gfdl/Marshall.Ward/CI/Gaea-stats-MOM6-examples/MOM6-examples/src/SIS2/src/ice_model.F90:2073
#3  0x950aad in coupler_init
	at /lustre/f2/dev/gfdl/Marshall.Ward/CI/Gaea-stats-MOM6-examples/MOM6-examples/src/coupler/coupler_main.F90:1809
#4  0x9457e7 in coupler_main
	at /lustre/f2/dev/gfdl/Marshall.Ward/CI/Gaea-stats-MOM6-examples/MOM6-examples/src/coupler/coupler_main.F90:611
#5  0x952895 in main
	at /lustre/f2/dev/gfdl/Marshall.Ward/CI/Gaea-stats-MOM6-examples/MOM6-examples/src/coupler/coupler_main.F90:313
```

**Comment by marshallward** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11844

**Comment by marshallward** [comment]
Round two: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11848

**Review by marshallward — APPROVED** [review]

**Pull request merged**
