### PR TITLE
Momentum budget terms multiplied by fractional layer-thicknesses

### PR DESCRIPTION
**Pull request by hmkhatri**
New diagnostics, i.e. momentum budget terms (`PFu/PFv`, `CAu/CAv` etc.) multiplied by fractional layer thicknesses have been added for momentum budget analysis. Fractional thicknesses are already computed in the barotropic step. These fractional thicknesses are now returned in the `btstep` subroutine call in the `MOM_dynamics_split_RK2` file and are used across different modules to compute required diagnostics. 

These depth-integrated budget term diagnostics would be useful in studying barotropic momentum and vorticity budgets, and the depth-integrated budget terms are also implemented in the diagnostics. 

@ashao @StephenGriffies @Hallberg-NOAA Could you please review it?

### CODE REVIEW

**Comment by StephenGriffies** [comment]
Thanks for this pull request @hmkhatri.  

We spoke about it during the MOM6 developers meeting today, 20 July 2020.  @Hallberg-NOAA and @adcroft are happy with the 2d diagnostics.  However, they wish to comment out the 3d diagnostics given that we do not know the proper remapping grid option and to retain these diagnostics might confuse future users/developers.  

Given that we might need to have these diagnostics for debugging in the future, we recommend commenting them and putting a note in the code at each comment.  At some point in the near future, after multiple applications of these diagnostics over some months, then we can remove the commented code.  But for the meantime, we should just leave the code but have it commented. 

Please make these changes and update your pull request, at which point we will run through the regression tests and move forward with bringing this code into the main trunk.  

Thanks again!  This is a good step forward with making MOM6 an analyst-friendly code.

**Comment by hmkhatri** [comment]
@StephenGriffies Thanks. I agree that the remapping option could be an issue in 3D diagnostics. As suggested, I have commented 3D diagnostics and put a note in all relevant places.

**Comment by StephenGriffies** [comment]
Thanks @Hallberg-NOAA for your careful review.  These changes should be straightforward.

**Comment by hmkhatri** [comment]
Thanks for the detailed comments @Hallberg-NOAA. I do not understand what you mean by "dOxygen comments".

I will change 2D arrays from pointer style to allocatable local arrays and deallocate them after use. Just to be sure, I should use the following style and deallocate after use, right?

```
real, allocatable, dimension(:,:) :: array_u
allocate(array_u(G%IsdB:G%IedB,G%jsd:G%jed))
if (allocated(array_u)) deallocate(array_u)
```

**Comment by StephenGriffies** [comment]
Take a look here for documentation of MOM6 code 

https://github.com/NOAA-GFDL/MOM6/wiki

In particular, see this page for Doxygen

https://github.com/NOAA-GFDL/MOM6/wiki/Doxygen

**Comment by hmkhatri** [comment]
@Hallberg-NOAA @StephenGriffies Thanks for the comments. I have implemented the suggested changes. All 3D diagnostics are now commented. For 2D diagnostics, allocatable arrays are used for initialization and these arrays are deallocated after the post-data step. All lines are under 120 characters in length.

**Comment by adcroft** [comment]
Testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/10886

**Comment by Hallberg-NOAA** [comment]
This passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/10886 .  It changes the contents of the MOM_parameter_doc files, so there will need to be an update to MOM6-examples after this PR is resolved on the MOM6 repository.

**Pull request merged**
