### PR TITLE
Solution for #1121

### PR DESCRIPTION
**Pull request by kshedstrom**
Don't update OBC tracer reservoirs inside the land mask or under the sea bed.

### CODE REVIEW

**Comment by MJHarrison-GFDL** [comment]
Looks good Kate

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/10454

**Comment by kshedstrom** [comment]
Hang on before merging - something I changed yesterday coughed up an out-of-bounds error.

**Comment by marshallward** [comment]
Updated Gaea regression test: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/10499

**Pull request merged**
