### PR TITLE
Generalize vertical remapping and neutral diffusion diagnostics

### PR DESCRIPTION
**Pull request by ashao**
This PR continues the reworking of tracer tendencies begun by @Hallberg-NOAA in PR #687 and #689.   
For the tracer content and concentration tendencies due to the vertical remapping and neutral diffusion, unit conversions were done inside those respective modules requiring special tracer-name dependent code. The registration of these diagnostics have been moved into the tracer registry and the conversion argument in register_diag used to handle the conversion.

I have ensured that this PR does not change the actual diagnostics in the model output. Some diagnostic names have changed; neutral diffusion flux diagnostics most notably since the df_x_2d and df_y_2d diagnostics already exist. 

Closes issue #699.

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
Overall, these look like very elegant modifications to the code, and I strongly support this restructuring.

  However, there are two issues that are evident from inspection of the changes that I would like to raise:

1) The accumulation of the diffusive tracer tendencies for a cell (dTracer) on lines 480-487 of MOM_neutral_diffusion.F90 are not rotationally invariant.  They could be made rotationally invariant by doing the sums across each face separately (e.g., dTracer_x1(k), dTracer_x2(k), dTracer_y1(k), dTracer_y2(k)), and then combining the 4 contributions for each cell with the right grouping (i.e., dTracer(k) = (dTracer_x1(k) + dTracer_x2(k)) + (dTracer_y1(k) + dTracer_y2(k)))

2) At line 391 of MOM_tracer_registry, there is a call to `print *, name`. In the interests of avoiding excessive verbiage in the MOM6 output from massively parallel models, please use MOM_note to write any informative messages, which would only cause the root PE to write this message.

**Comment by ashao** [comment]
@Hallberg-NOAA : Thank you for the comments and the suggestions. 
1. This is the way that I have it implemented on a branch with additional neutral diffusion development. Unless you have any objection, I'll hold off on this for now so that his PR only encapsulates changes that deal with diagnostics.
2. This was a debugging line. I usually grep for print statements before submitting, but forgot this time. I'll push a commit shortly removing it.

**Comment by Hallberg-NOAA** [comment]
This PR is being tested with pipeline https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/3189

**Comment by Hallberg-NOAA** [comment]
This PR changes answers slightly in several test cases. Was it intended to do so, and if so why does it change answers?

Also, the unit_tests test case fails to run; the variable "machep" is used before it is defined on line 507 of MOM_neutral_diffusion_aux.F90 with the intel compiler in debug mode.

**Comment by Hallberg-NOAA** [comment]
Sorry about the false alarm about the answer changes. I was comparing answers against an outdated reference; they do give the same answers. (Perhaps I ought not apply for any jobs with Hawaii's civil defense team.)

**Comment by ashao** [comment]
https://en.wiktionary.org/wiki/PICNIC

Thanks for finding that other little bug...take it down, patch it around, 127 little bugs in the code.

**Pull request merged**
