### PR TITLE
+Add option to write shorter available diags files

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
Added the option to write out available diags files that avoid having a huge
number of redundant entries related to alternative diagnostic grids or module
names and derived quantities like spatial averages.  In this case, these
alternative variants are documented in the available diags files with a brief
'variants' line.  A new runtime parameter, FULL_AVAILABLE_DIAGS_LIST, was added
to enable this new behavior; by default the available diags files look like they
did previously, but this might be the exception to the rule where code changes
should not change output by default.  Also cleaned up some non-standard code
style (like white-space) in MOM_diag_mediator.  All answers are bitwise
identical, but there is a new entry in the MOM_parameter_doc.all files.

  Discussion on the right default for FULL_AVAILABLE_DIAGS_LIST would be helpful.

  This PR addresses MOM6 issue #1224, which might be closed after this PR is accepted.

### CODE REVIEW

**Comment by adcroft** [comment]
- Split the list of modules and vars (currently in variants)
- Expand out list of options rather than introduce a new syntax

**Comment by adcroft** [comment]
I think you can drop the option to keep old format - not sure anyone would want to maintain the old files.

**Comment by Hallberg-NOAA** [comment]
This PR was just updated to always use the new, shorter available_diags format, as suggested in reviews.

  Revised the new available_diags format in response to reviews, including
explicitly listing all variable and module names, and always writing the
available_diags file in the new shortened format.  This includes removing the
recently added runtime parameter FULL_AVAILABLE_DIAGS_LIST.  All answers are
bitwise identical, but there are substantial changes in the available_diags
files, and the MOM_parameter_doc files no longer are changed by this PR.

**Comment by marshallward** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11615

**Pull request merged**
