### PR TITLE
Rotate vels

### PR DESCRIPTION
**Pull request by kshedstrom**
This adds an option to save true north ssu and ssv, required for our BOEM contract. There are similar changes to SIS2.

### CODE REVIEW

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
These changes look good to me, but I do have one change that I would like to request.  In the upcoming set of revisions to give rotational symmetry with Fused-Multiply-Adds (FMAs), we are going to be writing expressions like `Ax * Bx + Ay * By` as `(Ax * Bx) + (Ay * By)` so that the compiler does not have the option of fusing the x- or y- parts of the expressions but not the other one.  It would be helpful if you could revise the expressions for `ssu_east` and `ssv_north` to either add the parentheses to prevent FMAs from adding an asymmetry, or at least write these expressions so that the `cos_rot` terms come first in both cases.  This is, of course, a diagnostic so perhaps we need not be so particular here, but for a new contribution like this, it is probably easier to make this small change now rather than coming back to it later.

**Review by Hallberg-NOAA — APPROVED** [review]
Thank you for this updated PR.

**Comment by marshallward** [comment]
@kshedstrom Can you enable "Allow rebase merging" in the Settings of ESMG/MOM6?  This would allow us to update this PR to the latest dev/gfdl.

**Comment by kshedstrom** [comment]
It looks like it is already set. Is it not behaving that way?

**Comment by marshallward** [comment]
I'm not able to update this PR.  But let's try to sort this out privately.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/23445 :heavy_check_mark:  :yellow_circle: 

This requires an update to `available_diags.000000`

**Comment by marshallward** [comment]
This PR was rebased into this commit: https://github.com/NOAA-GFDL/MOM6/commit/bb8a6533178533289b92847153ee0612aec1903c

**Pull request closed without merging**
