### PR TITLE
wave structure computation into wave_speeds

### PR DESCRIPTION
**Pull request by raphaeldussin**
wave_speeds now computes the wave structures
(eigenvectors) for each mode speed (eigenvalue)
similarly to the wave_speed (singular) function.
This is a replacement for the MOM_wave_structure
function, which could be removed in a subsequent PR.

Additional arrays for mode structures and integral
quantities are passed as output hence this is a
breaking change for the call to wave_speeds.
However it is only called once in diabatic_driver
and is used exclusively for internal tides ray tracing.
This also requires to make int_tides structure public,
this could be reverted by moving wave_speeds into
MOM_internal_tides if necessary in a following PR.

The dimensional solutions for the wave structures are 
now computed inside MOM_internal_tides, and new 
diagnostics are added.

An out-of-bounds bug is also corrected for the computation 
of an averaged Coriolis parameter.

### CODE REVIEW

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
Thank you for this PR.  For the most part, this looks like it should work, but there is something about this PR has me confused.  Why was it necessary to move the subroutine `wave_speeds()` from MOM_wave_speed to MOM_internal_tides?  Unless there is a compelling reason for this move, I think that it should be returned to the MOM_wave_speed module.

  This structure is problematic because `wave_speeds()` is still using the same `wave_speed_CS` control structure from the MOM_wave_speed module, which is now being made transparent.  It is also problematic because it makes it hard to see what changes needed to be made in `wave_speeds()` to make it work properly.

  This PR passes our testing, but this could be mostly because the impacted code is not being exercised by our testing.  The visual inspection of these changes is therefore all the more important.  If the move between modules is in fact necessary for some compelling reason, please consider making these changes in two separate PRs, one of which makes the necessary code changes, and the other does nothing other than move the wave_speeds subroutine.

**Comment by raphaeldussin** [comment]
The move of `wave_speeds` into the `MOM_internal_tides` module was suggested in dev meeting so that we don't need to expose the `internal_tides_CS` in `MOM_diabatic_driver` during the call to `wave_speeds`, the later has been moved out of `MOM_diabatic_driver` and into `propagate_int_tide` also to keep `int_tides_CS` private. `wave_speeds` indeed uses a now public `wave_speed_CS` but only reading in parameters, no arrays are passed through this structure. This seemed like a safe solution that avoid duplicating the control structure. Regarding the refactoring, this PR can be decomposed into 3 steps:

commit 1: changes to the `wave_speeds` code, this is the only answer changing part
commit 2: removed the now unused `wave_structure` code
commit 3: refactoring: move `wave_speeds` into `MOM_internal_tides`

I can split into 3 different PRs if that's easier to review, with the drawback of adding to the regression pipeline.

**Review by Hallberg-NOAA — APPROVED** [review]
These changes have addressed the primary issues with the previous version.  There should be some future refactoring which will avoid the need for transparent types, but holding this up any longer would be disruptive of important development efforts.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/19452 :heavy_check_mark:

**Pull request merged**
