### PR TITLE
Dev master candidate 2018 05 15

### PR DESCRIPTION
**Pull request by adcroft**
The diff for this PR shows a lot changes due to extensive doxygenization of APIs.

As usual we'll only accept the PR once we've heard from everyone that it does not break anything.

There are answer changes in here:
- 48e90d0b928457e64c80b065c32f1131cc6b6dfb "Use rho_ref in finite volume PGF density calcs"

MOM6-examples has a corresponding branch "dev-master-candidate-2018-05-15".

### CODE REVIEW

**Comment by kshedstrom** [comment]
No problems here from the short tests (CCS1 is still in the queue).

**Comment by gustavo-marques** [comment]
@adcroft I am getting the following error:
MOM6-examples/ice_ocean_SIS2/OM4_05/ocean.stats.intel: FATAL from PE 253: grid_mod/get_grid_version: Can't determine the version of the grid spec: none of "x_T", "geolon_t", or "ocn_mosaic_file" exist in file "INPUT/grid_spec.nc"

Do I need to update grid_spec.nc?

**Comment by gustavo-marques** [comment]
After updating the data-sets, I was able to reproduce the answers obtained on Gaea (intel/17.0.1).

I approve this PR.

**Comment by kshedstrom** [comment]
I approve this PR too.

**Pull request merged**
