### PR TITLE
changed max_file_size to 100 GB for case when large_file_support = true

### PR DESCRIPTION
**Pull request by wrongkindofdoctor**
The max_file_size was increased from 4 GB to 100 GB (1e11 bytes) for instances when large_file_support is true (default) in MOM_restart. Otherwise, the max_file_size is 2 GB. MOM6 must be compiled with the flag -Duse_LARGEFILE to set the output netCDF file format to 64-bit offset on Gaea. This change permits removing the capability to write uncombined restart files. The 'ncks' fre tool may be used to combine uncombined restart files generated from simulations run with an older version of the model.

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
Trailing white space is not permitted in MOM6 code, and this is automatically flagged during the continuous-integration tests. Please update the code in this PR to remove the trailing white space on line 886 of MOM_restart.F90.  Thank you.

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/4195

**Comment by Hallberg-NOAA** [comment]
Thank you for your propsed changes, @wrongkindofdoctor. However, we need to be cautious here. Until _all_ of the post-processing and data analysis software that is in use is compiled with NetCDF-4.4 or later (i.e., release dates after November 2015, when the NC_64BIT_DATA option was introduced), we will be using the older 64-bit-Offset netCDF format, for which the limit is 2^32-4.  For a fuller discussion of NetCDF file size limitations, see
https://www.unidata.ucar.edu/software/netcdf/netcdf-4/newdocs/netcdf/64-bit-Offset-Limitations.html

  The proposed change would essentially break support for the standard 64-bit-Offset mode.  I think this is a bad idea. However, there is no need to retain support for the much older NetCDF classic format, which predates the 2005 release of NetCDF 3.6.1.  I think that we should consider obsoleting the LARGE_FILE_SUPPORT flag, and introducing a new flag, something like USE_64BIT_DATA, for use when we are using NetCDF-4.4 or later.

**Comment by Zhi-Liang** [comment]
Hi Bob,

  I think it is a great idea to introduce a new flag like USE_64BIT_DATA.
Since this is only for restart file, the tools I think need to be tested
are the following: mppnccombine, nco, ferret, ncview and fregrid. Please
add if there is other tools.

Greetings,

Zhi

**Comment by Hallberg-NOAA** [comment]
In accordance with this discussion, we will be obsoleting LARGE_FILE_SUPPORT and adding a new flag, USE_64BIT_DATA. The current PR does not move us in that direction, but it was a useful discussion. Thank you, @wrongkindofdoctor , for initiating this PR.

**Pull request closed without merging**
