### PR TITLE
Add ability to include tides in bottom velocity component for BBL.

### PR DESCRIPTION
**Pull request by breichl**
- When BBL_USE_TIDAL_BG is true, MOM_set_viscosity.F90 now reads in the RMS tidal velocity from the tideamp_file and then uses the square of the RMS tidal velocity in place of the background velocity squared to compute bottom friction.
- Adds a flag to read from tide file (BBL_USE_TIDAL_BG)
- Uses an existing input for the tide file filename (TIDEAMP_FILE)
- Also adds two new diagnostic output fields: 'bbl_u' and 'bbl_v' that output the mean bottom velocity used in the bottom friction calculation.

### CODE REVIEW

**Comment by marshallward** [comment]
This is crashing because `CS%bottomdraglaw` is false and `BBL_USE_TIDAL_BG` is unread, so `CS%BBL_use_tidal_bg` is uninitialized.  It's getting set with garbage and being interpreted as `.true.`.

You may need to nest the loop at L2096.

**Comment by breichl** [comment]
Thanks Marshall. I will move it up to be nested with the CS%bottomdraglaw loop.

**Comment by marshallward** [comment]
Gaea regression testing: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/9695

**Comment by marshallward** [comment]
The regression fail is solely due to the new diagnostics `bbl_u` and `bbl_v`, so there are otherwise no regressions and I will merge this now.

This requires a parameter update to MOM6-examples which I'll also update.

**Pull request merged**
