### PR TITLE
Fix a bug in porous barriers

### PR DESCRIPTION
**Pull request by herrwang0**
This PR fixes a minor bug in porous barriers module.

It may change answers for some very rare cases in barotropic runs. For an example I tested with barotropic tides, the answer is unchanged at bit level. 

(PS: this is a redo of PR #726, leaving out the default parameter change part).

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
These changes seem innocuous to me, but I do not understand the nature of the bug that is being fixed.  It looks to me as though the various fields that are being set more explicitly now were already being set properly before. Please describe the bug more explicitly in the descriptive comments.

**Comment by herrwang0** [comment]
> These changes seem innocuous to me, but I do not understand the nature of the bug that is being fixed. It looks to me as though the various fields that are being set more explicitly now were already being set properly before. Please describe the bug more explicitly in the descriptive comments.

The logical for the current algorithm is as follows: If the top interface height in layer `k` is above the highest topography (`D_max`), then variable `do_I` is changed to false, so that calculations for all layers above layer `k` are skipped, as these layers are above the topography and their porous barrier coefficients are unity. 

Without the fix, it can potentially problematic when a layer starts with a smaller-than-one coefficient but subsequently moves above the highest topography. In the case, the coefficient of this layer would never get reset back to unity.

**Review by Hallberg-NOAA — APPROVED** [review]
Thank you, @herrwang0,  for the clarification in the discussion of the nature of the bug that is being fixed.  I understand this issue now.  I now agree that these changes are both useful and necessary.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/25106 :heavy_check_mark:

**Pull request merged**
