### PR TITLE
Main candidate from NCAR (12/15/2020)

### PR DESCRIPTION
**Pull request by gustavo-marques**
## Major changes

* Make long character variables deferred length (https://github.com/NCAR/MOM6/pull/165)

* Major updates to the lateral boundary diffusion module (https://github.com/NCAR/MOM6/pull/164)

* Introduce a controllable stdout unit in MOM_io (https://github.com/NCAR/MOM6/pull/163)

## New diagnostics

* Adds option to output u^2, v^2 and u*v (https://github.com/NCAR/MOM6/pull/159)

This candidate **does not** changes answers for the MOM6 regression tests (Intel 19.0.5).

### CODE REVIEW

**Comment by marshallward** [comment]
@gustavo-marques I am seeing a `unit_tests` fail in our GNU debug build:
```
 MOM_lateral_boundary_diffusion, UNIT TEST FAILED: Equal hbl and same layer thicknesses (gradient from right to left)
Layer=  1 F_calc=  0.0000000000000000 F_ans -2.0000000000000000                 
Layer=  2 F_calc=  0.0000000000000000 F_ans  0.0000000000000000                 FATAL: MOM_unit_tests: near_boundary_unit_tests FAILED
```
Do you want to look into this?  Can you try to reproduce?

**Comment by adcroft** [comment]
@jiandewang, @kshedstrom, @abozec (or @awallcraft) can you review/test this PR per usual process? We're fairly happy with it other than the above unit test issue but continue to test.

**Comment by gustavo-marques** [comment]
@marshallward, it passed all unit tests with Intel 19.0.5. Let me try with GNU...

**Comment by marshallward** [comment]
I get a fail on Intel 18.0.6 (with slightly more info since it's a REPRO build):
```
 MOM_lateral_boundary_diffusion, UNIT TEST FAILED: 
 Equal hbl and same layer thicknesses (gradient from right to left)             
  
Layer=  1 F_calc=  0.0000000000000000 F_ans -2.0000000000000000
Layer=  2 F_calc=  0.0000000000000000 F_ans  0.0000000000000000
 MOM_lateral_boundary_diffusion, UNIT TEST FAILED: 
 Equal hbl and same layer thicknesses (gradient from left to right)             
  
Layer=  1 F_calc=  0.0000000000000000 F_ans  1.0000000000000000
Layer=  2 F_calc=  0.0000000000000000 F_ans  0.0000000000000000
Layer=  1 F_calc= -1.0000000000000000 F_ans -1.0000000000000000
 MOM_lateral_boundary_diffusion, UNIT TEST FAILED: 
 hbl < column thickness, hbl same, linear profile right, khtr=2                 
  
Layer=  2 F_calc=  0.0000000000000000 F_ans -4.0000000000000000
Layer=  1 F_calc=  0.0000000000000000 F_ans  0.0000000000000000
Layer=  2 F_calc=  0.0000000000000000 F_ans  0.0000000000000000
 MOM_lateral_boundary_diffusion, UNIT TEST FAILED: 
 Different hbl and different column thicknesses (gradient from left to right)   
  
Layer=  1 F_calc=  0.0000000000000000 F_ans 10.0000000000000000
Layer=  2 F_calc=  0.0000000000000000 F_ans  0.0000000000000000

FATAL: MOM_unit_tests: near_boundary_unit_tests FAILED
```

I'll try to repeat this with Intel 19.

**Comment by gustavo-marques** [comment]
Okay, I found the problem (I thought I had merged this https://github.com/NCAR/MOM6/pull/169, but apparently I did not). I will send a fix in a few.

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by marshallward** [comment]
I still seem to be getting a fail, although I am now getting different answers (-0.4 rather than 0.0):
```
 MOM_lateral_boundary_diffusion, UNIT TEST FAILED: Equal hbl and same layer thicknesses (gradient from right to left)              
Layer=  1 F_calc= -0.4000000000000000 F_ans -2.0000000000000000
Layer=  2 F_calc=  0.0000000000000000 F_ans  0.0000000000000000

FATAL: MOM_unit_tests: near_boundary_unit_tests FAILED
```
Could be something to do with the merge; I will pick this up tomorrow.

**Comment by marshallward** [comment]
I just tried an Intel "REPRO" build and it did pass, so there could still be an underlying problem here (e.g. assumed zero initialization?).

I don't know anything about this test, so I won't be able to sort this out quickly, but I'll start looking into it.  In the meantime, can you re-try your test using GNU?

**Comment by gustavo-marques** [comment]
Thanks, @marshallward. I will try to reproduce the fail with GNU.

**Comment by awallcraft** [comment]
I approve this PR.

**Comment by gustavo-marques** [comment]
@marshallward, I was able to reproduce the fail with GNU in debug mode. The test is failing because of an undefined `logical` in the unit test function `CS%limiter_remap`. For some reason, GNU/debug sets it to True by default. The fix coming in a few.

**Comment by jiandewang** [comment]
EMC wcoss machine is reserved for production test only at this moment, will test this MOM code once access to machine is back

**Comment by marshallward** [comment]
Thanks, @gustavo-marques , good to see it was nothing serious.  This is now passing on our branch with no regressions (after resolving a minor git conflict).

**Review by Hallberg-NOAA — APPROVED** [review]
I have visually examined all of these code changes, and I approve of them. (I especially like the use of the deferred allocation character strings, which is a very elegant solution!) Also, I have been informed that this PR is now passing all of the testing from the GFDL side.

**Comment by Hallberg-NOAA** [comment]
The merge of this PR onto the main branch is now just waiting for the go-ahead from the EMC team via @jiandewang, having obtained approval from the other main forks.

**Comment by jiandewang** [comment]
I shall have access to machine this afternoon, will try to finish testing no later than today

**Comment by jiandewang** [comment]
works fine on EMC (PS: I started my testing 1 minute after machine is back, so my job got finished quickly as nodes are empty)

**Comment by marshallward** [comment]
Approvals:
* NCAR (submitted)
* FSU
* GFDL
* Rutgers
* EMC

I am going to merge this now.

**Pull request merged**
