### PR TITLE
189 h to m

### PR DESCRIPTION
**Pull request by nicjhan**

### CODE REVIEW

**Comment by nicjhan** [comment]
OK, I've made the changes suggested by @Hallberg-NOAA, it should not be ready to merge.

**Comment by adcroft** [comment]
Typo? "not" or "now"?

**Comment by nicjhan** [comment]
Yes, a typo

**Comment by nicjhan** [comment]
I have made the changes we talked about: i.e. moving the H <-> m conversion into the ALE grid generation. This means that there's no need to switch H_to_m before calling ALE_main(). It should now be ready to merge.

**Pull request merged**
