### PR TITLE
EMC update 20210322

### PR DESCRIPTION
**Pull request by marshallward**
This PR is an update from EMC courtesy of @jiandewang.

We are merging this directly into `dev/gfdl` due to a mistake on our part where we prematurely merged `dev/gfdl` into `main`.  These premature unreviewed commits ended up in `dev/emc` fork before we detected our mistake.  Once approved for merge into `dev/gfdl`, we will then submit this to `main` for review ASAP.

Summary of changes (provided by @jiandewang):
* fixed missing halo in two halo updates for taux and tauy in mom_surface_forcing_nuopc.F90 in nuopc_cap
* allow MOM6 to use a mesh optionally in nuopc_cap
* fixed sign error on fprec passed to ocean in mom_surface_forcing_nuopc.F90 in nuopc_cap (from NCAR)
* allow ocean->land topo edits in MOM_shared_initialization.F90

### CODE REVIEW

**Comment by marshallward** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/12325

**Comment by marshallward** [comment]
@gustavo-marques Do you mind quickly reviewing this?  I am going to send it to `main` as well but would be best to get your feedback now.

**Review by Hallberg-NOAA — DISMISSED** [review]
This is an answer-changing bug fix in the sign of frozen precipitation contributions to the latent heat fluxes, and I agree that this is a bug.  We need to either get explicit buy-in from absolutely everyone that they want the code to irretrievably change answers using the mct and nuopc caps, without the ability to recreate the current answers, or we need to use a run-time flag to correct this bug.  

  If there any published papers that use the current (buggy) version, or even experimental runs that people find interesting, I strongly suspect that we will need a run-time bug-fix flag for these changes, and the default at first should be to keep the bug.  We can move aggressively to change the default, and then more deliberately to obsolete and eliminate the bug-fix flag.

**Comment by jiandewang** [comment]
@marshallward  In your branch,

https://github.com/CVMix/CVMix-src/blob/9423197f894112edfcb1502245f7d7b873d551f9/src/shared/cvmix_tidal.F90#L807-L823

here rho is not defined as optional, but in

https://github.com/marshallward/MOM6/blob/emc_update_20210322/src/parameterizations/vertical/MOM_tidal_mixing.F90#L883-L887

you removed rho

**Comment by marshallward** [comment]
@jiandewang `dev/gfdl` recently updated its CVMix source, so it would be good for you to check that there were no consequences.  (I didn't handle this but it did not appear to be answer-changing).

**Review by adcroft — APPROVED** [review]

**Comment by gustavo-marques** [comment]
This PR is changing answers for us but I do not believe the reason is the bug fixes in MCT and NUOPC. The answer-changing bug fixes are already implemented in dev/ncar (https://github.com/NCAR/MOM6/pull/174). We have notified, ~ 2 months ago, people that we know are affected by these changes. They were all okay with them. 

We need to do a more thorough evaluation to find out what commit(s) is(are) changing answers. I will start by evaluating dev/gfdl. In terms of the changes being proposed here, I approve this PR.

**Comment by marshallward** [comment]
Thanks @gustavo-marques  @jiandewang

@jiandewang : I'd like to merge this into `dev/gfdl` and hopefully send to `main` some time today.

I don't mind waiting if you prefer, but you will also get a chance to test this during the `dev/gfdl` -> `main` review period (where there is no hurry) so that would also work for us.

**Comment by jiandewang** [comment]
@marshallward then do as you planned
@gustavo-marques I merged dev/gfdl to dev/emc and made a test run in UFS, first several jobs finished without answer change, other jobs are waiting in the queue, shall have black and white answer in 2 hours

**Comment by marshallward** [comment]
Great, thanks all.  We will merge this to `dev/gfdl` ASAP and then will resolve any answer changes in the `dev/gfdl` -> `main` candidate.

**Review by adcroft — APPROVED** [review]

**Comment by Hallberg-NOAA** [comment]
I am withdrawing my requested changes because everyone we are aware of who might be using the NUOPC or MCT couplers has indicated that they are on-board with these changes, some of which are already on the dev/ncar branch.

**Pull request merged**
