### PR TITLE
Dev/ncar candidate 2019 01 04

### PR DESCRIPTION
**Pull request by gustavo-marques**
This PR adds new capabilities to MOM6, including new fluxes that are needed in CESM. Currently, the changes added here are only available via MCT driver. All answers in MOM6-examples are b4b with respect to the latest dev/master (only Intel was checked).

Below is a summary of the main changes:

[* Add additional fluxes needed in CESM
](https://github.com/NCAR/MOM6/pull/87)

[* Rotate fields from local to true lat/lon coordinates and vice-versa ](https://github.com/NCAR/MOM6/pull/88)

### CODE REVIEW

**Comment by adcroft** [comment]
There will be a delay before this can be handled. The government shutdown means I have no computers on which to do testing, and federal employees are not allowed to work (which includes reviewing PRs).

**Comment by gustavo-marques** [comment]
Following the last MOM6 dev meeting, I've pushed new commits to rename `meltw` and `melth` to `seaice_melt` and `seaice_melt_heat`, respectively. I've also renamed `heat_content_meltw` to `heat_content_icemelt`. All answers in MOM6-examples are b4b with respect to the latest dev/master (only Intel was checked).

**Comment by gustavo-marques** [comment]
I noticed the description for the `heat_content_*` variables says `"Heat content (relative to 0degC) of"` (e.g., see [here](https://github.com/NOAA-GFDL/MOM6/blob/a39bc70a686e21afc9352e3022cffb03e410b1fa/src/core/MOM_forcing_type.F90#L1382)), but if fact, these values are computed with respect to SST (e.g, see [here](https://github.com/NOAA-GFDL/MOM6/blob/a39bc70a686e21afc9352e3022cffb03e410b1fa/src/core/MOM_forcing_type.F90#L693)). Should we fix that? See also [this comment](https://github.com/NOAA-GFDL/MOM6/blob/a39bc70a686e21afc9352e3022cffb03e410b1fa/src/core/MOM_forcing_type.F90#L699) from @adcroft.

**Comment by kshedstrom** [comment]
Can I ask you to tag the candidate code as such? Or is it your dev/master?
Thanks.

**Comment by adcroft** [comment]
Good news! We have limited access to a machine again *and* this PR passes our tests (with a minor infraction):
- there were three lines of source code of excessive length. I've lined up hot-fixes as part of the merge so we don't unnecessarily delay this PR further.

@kshedstrom @awallcraft Any other comments? We're ready to merge this here.

**Comment by gustavo-marques** [comment]
@kshedstrom Sorry, I don't follow your questions. Are you suggesting that we should create a tag for this candidate rather than having it as a branch? If so, what's the advantage of doing this?

**Comment by kshedstrom** [comment]
I just need to know what branch it is. Since I don't have permission to
accept the pull request, I don't have all the information via github.
Easiest for me is to "git fetch ncar" or "git fetch gustavo", depending,
then checkout the relevant branch. I do see the diff/patch files and could
download one, then apply it, but I already merged Bob's update, so that
could be risky.

**Comment by adcroft** [comment]
I think Kate is looking for this:
```bash_
git checkout -b gustavo-marques-sync_dev_master_19Dec18 dev/master
git pull https://github.com/gustavo-marques/MOM6.git sync_dev_master_19Dec18
```

**Comment by kshedstrom** [comment]
Thank you, @adcroft!
All is good from here.

**Comment by kshedstrom** [comment]
I spoke too soon. Oddly, it changes answers for my Chapman_coast slump and tall_slump cases only.

**Comment by adcroft** [comment]
@kshedstrom Did those tests pass on dev/master without the PR, or is the difference between dev/master and dev/esmg ?

**Comment by kshedstrom** [comment]
Yes, turns out to be a difference between dev/gfdl and dev/master. I must have missed it some other time.

**Comment by kshedstrom** [comment]
Hah, it's the difference in the circle_OBC initialization of h code between the two branches.
Alll is good for the PR.

**Comment by kshedstrom** [comment]
I had to check - it's my DISK_X_OFFSET stuff from last June.

**Pull request merged**
