### PR TITLE
dev/master candidate 2018-07-16 from dev/gfdl

### PR DESCRIPTION
**Pull request by adcroft**
This is a humongous pull request (177 files, 301 commits) but it is almost all doxumentation (doxygen + comments). There are three content changes:

- Staggered calculation of kappa-shear (4475187, #801)
- Anisotropic viscosity (e6e32c7, #799)
- OBC cleanup

This is a PR to dev/master so needs evaluation by relevant parties. We'll wait for review/thumbs up before we merge into dev/master.

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by adcroft** [comment]
@gustavo-marques, @awallcraft, @jiandewang ?

**Comment by gustavo-marques** [comment]
MOM6-examples run on Cheyenne give identical answers to those from [Gaea](https://github.com/adcroft/Gaea-stats-MOM6-examples/tree/dev-master-candidate-2018-07-16) (only intel).  No change in answers for MOM6-cases/cesm/T62_g16. 

I approve this PR.

**Comment by jiandewang** [comment]
testing shows this PR works fine for NCEP coupled system, I approve this 
PR.  -- Jiande

**Pull request merged**
