### PR TITLE
Inline harmonic analysis

### PR DESCRIPTION
**Pull request by c2xu**
Set default HAready = False

Also made additional adjustment to ensure harmonic analysis is not activated if tide is not used in the model.

### CODE REVIEW

**Comment by c2xu** [comment]
This PR should fix issue #708

**Comment by kshedstrom** [comment]
Yes, thank you, that fixes my Supercritical case (and makes the Arctic hycom troubles something else entirely).

**Review by marshallward — COMMENTED** [review]
I'm looking over this module, and I'm a bit uncomfortable with the use of `return` in so many functions, particularly with respect to the various parameter tests.  In most cases, one could have moved the logic outside the function and avoided the function call altogether.

I was also a bit surprised that `HA_CSp` is not only a pointer but also a local variable that conditionally points to `CS%HA_CSp`.  That is, the null state is being used to control the logical flow.

I don't want to block this PR over those concerns, but it might be a good idea to review this design later when we have a chance.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/24731 :heavy_check_mark:

**Pull request merged**
