### PR TITLE
Dev master candidate NCAR 03/27/2020

### PR DESCRIPTION
**Pull request by gustavo-marques**
Summary:
* Add module `MOM_lateral_boundary_diffusion`. This module calculates and applies diffusive fluxes as a parameterization of lateral mixing (non-neutral) by mesoscale eddies near the top and bottom (to be implemented) boundary layers of the ocean. See [#135](https://github.com/NCAR/MOM6/pull/135) for further details

* Create NCAR fork of Doxygen [#123](https://github.com/NCAR/MOM6/pull/123)

* Modify MEKE to allow GME to work properly [#128](https://github.com/NCAR/MOM6/pull/128)

* Adds option to scale KHTH with depth [#127](https://github.com/NCAR/MOM6/pull/127)

* Add option to pass river runoff via `data_override` in the NUOPC cap  [#130](https://github.com/NCAR/MOM6/pull/130)

* Create a separate param for `MEKE` bottom drag [#131](https://github.com/NCAR/MOM6/pull/131)

* Fix bugs in `Leith` add new input parameter [#134](https://github.com/NCAR/MOM6/pull/134)

* Fix bugs caught by GNU compiler [#141](https://github.com/NCAR/MOM6/pull/141)

* Fix a bug in `thickness_diffuse` when using `MEKE_GEOMETRIC` [#143](https://github.com/NCAR/MOM6/pull/143)

* Update `GME` by removing its dependency on `MEKE` [#144](https://github.com/NCAR/MOM6/pull/144)

* OMP directives fixes [#146](https://github.com/NCAR/MOM6/pull/146), [#142](https://github.com/NCAR/MOM6/pull/142)

This PR does not change answers for the GFDL tests when evaluated against the latest dev/master (intel/17.0.1). However, it adds the following runtime parameters:

```
MEKE_GEOMETRIC_ALPHA = 0.05     !   [nondim] default = 0.05
                                ! The nondimensional coefficient governing the efficiency of the GEOMETRIC
                                ! thickness diffusion.
```

```
MEKE_EQUILIBRIUM_RESTORING = False !   [Boolean] default = False
                                ! If true, restore MEKE back to its equilibrium value, which is calculated
                                ! ateach time step.
```

```
CDRAG_MEKE = 0.003              !   [nondim] default = 0.003
                                ! CDRAG is the drag coefficient relating the magnitude of the velocity field to
                                ! the bottom stress.
```
```
DEPTH_SCALED_KHTH = False       !   [Boolean] default = False
                                ! If true, KHTH is scaled away when the depth is shallower than a reference
                                ! depth: KHTH = MIN(1,H/H0)**N * KHTH, where H0 is a reference depth, controlled
                                ! via DEPTH_SCALED_KHTH_H0, and the exponent (N) is controlled via
                                ! DEPTH_SCALED_KHTH_EXP.
```

```
ADD_LES_VISCOSITY = False       !   [Boolean] default = False
                                ! If true, adds the viscosity from Smagorinsky and Leith to the background
                                ! viscosity instead of taking the maximum.
```

```
NDIFF_INTERIOR_ONLY = False     !   [Boolean] default = False
                                ! If true, only applies neutral diffusion in the ocean interior.That is, the
                                ! algorithm will exclude the surface and bottom boundary layers.
```

```
USE_LATERAL_BOUNDARY_DIFFUSION = False !   [Boolean] default = False
                                ! If true, enables the lateral boundary tracer's diffusion module.
```

### CODE REVIEW

**Comment by adcroft** [comment]
As per usual can @awallcraft, @kshedstrom and @jiandewang evaluate this PR.

**Comment by marshallward** [comment]
I've run the (not-yet-merged) rotational tests and these tests have passed.

And I second the proposal to reconsider phasing out multi-statement lines!

**Comment by gustavo-marques** [comment]
> I've run this through our tests which all passed (as you knew it would).
> 
> I especially liked the bug catch ([NCAR#141](https://github.com/NCAR/MOM6/pull/141)) that is a good example of why we perhaps should not allow single-line multi-statements. Thank goodness for the gnu compiler!
> 
> My only query is about the naming of CDRAG_MEKE. With one exception, every other MEKE parameter is named MEKE_* so could we have this renamed to MEKE_CDRAG for consistency?

Done.

**Comment by adcroft** [comment]
With the new parameter name GFDL team is ready to accept this PR. Now over to @jiandewang, @awallcraft @kshedstrom

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by awallcraft** [comment]
I approve this PR.

**Comment by jiandewang** [comment]
works fine in NCEP UFS, approval this PR

**Pull request merged**
