### PR TITLE
Dev master candidate 2018 04 22

### PR DESCRIPTION
**Pull request by adcroft**
This PR is to merge dev/gfdl as of 2019-04-22 onto dev/master. There are a dozen or so merges here but the big one is #896 that affects top-level APIs. There are no (known) answer changes but parameter documentation files are affected. There is a corresponding branch of MOM6-examples with updated doc files but the parameter docs for you own experiment repositories should be checked.

- PR #896 New options to control time-stepping at coupler interfaces
- PR #909 Re-factor of Travis-CI
- PR #908 Catch renamed variables in restarts
- PR #905 Dimensional scaling of Coriolis
- PR #869 FV re-sampling of diagnostics (data reduction x2)
- PR #886, #881, #877 documentation fixes
- PR #873 Incorporate fixes added to dev/master
- PR #867 Fixes for dimeionsal terms in OBCs
- PR #897, #866 OpenMP fixes
- PR #864 Dimensional scaling of the z-direction
- PR #868 Bug fix for post_data() segmentation fault
- PR #863 Bug fix for Langmuir number

As per usual feedback from @gustavo-marques, @awallcraft, @kshedstrom and @jiandewang is asked for before we accept this PR.

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by gustavo-marques** [comment]
It does not change answers for us, so I approve it.

**Comment by awallcraft** [comment]
I approve this PR.

Alan.

**Comment by jiandewang** [comment]
the newly introduced argument "US" in src/core/MOM_forcing_type.F90 
subroutine register_forcing_type_diags(Time, diag, US, use_temperature, handles, use_berg_fluxes)
caused the EMC-NCAR unified cap failed in compiling, EMC and NCAR will need to make corresponding modification in the cap code config_src/nuopc_driver/MOM_surface_forcing.F90

**Comment by Hallberg-NOAA** [comment]
Sorry about the oversight with the nuopc_driver code.  When we added the changes in question to the dev/gfdl code, the nuopc_driver had not yet been merged in, and of course our testing did not include the nuopc_driver when we merged it into dev/gfdl.  We might need to think about how we handle testing in cases like this that might impact the various sets of top-level driver/cap code.

  I just updated the nuopc_driver code to include the new missing unit_scaling_type arguments.  We have now partially compiled the updated code with the nuopc_driver (as far as we can go without access to the other ESMF or nuopc code), and we believe that this should compile and run correctly with the nuopc_driver.  @jiandewang, please try updating the code in this PR and see if it is working correctly for you now.

**Comment by jiandewang** [comment]
Bob:
  Thanks for your quick action, I will make a new try and let you know the
results.

Cheers,
Jiande

**Comment by jiandewang** [comment]
It works fine now in EMC Unified Coupling System. I approve this PR.

**Comment by gustavo-marques** [comment]
I just compiled the NCAR/NUOPC cap and it is working for us too.

**Comment by adcroft** [comment]
Good - I'll make the merge and then we can send out the second PR as discussed on the Monday call.

BTW. did no one notice I got the year wrong in the branch name?

**Pull request merged**
