### PR TITLE
Mask table fix

### PR DESCRIPTION
**Pull request by kshedstrom**

### CODE REVIEW

**Review by Hallberg-NOAA — COMMENTED** [review]
The changes to MOM_open_boundary here seem sensible enough and are well explained in the discussion.

I don't understand why the MOM_CFC_cap fix is showing up in this PR.  It is correct, but I would think that it should appear in a separate PR to MOM6.  @marshallward, do you understand how or why the MOM_CFC_cap fix is here?

  I would be happy to approve this once we understand whether we should be accepting the MOM_CFC_cap fix as a part of this PR.

**Comment by kshedstrom** [comment]
Sorry, can you pull it out?

**Comment by marshallward** [comment]
@kshedstrom Not easily, but I can remove it if I do a command-line merge.  Seems like this has otherwise been approved so I will do that.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/21708 :heavy_check_mark: (Parameters are not out of date, despite warnings).

**Review by marshallward — APPROVED** [review]
Approved OBO @Hallberg-NOAA

**Comment by marshallward** [comment]
This has been merged to dev/gfdl.  The hashes have changed, so I have to manually close this PR.

**Pull request closed without merging**
