### PR TITLE
Dev master candidate 2018-10-15

### PR DESCRIPTION
**Pull request by adcroft**
This PR is to merge dev/gfdl as of 2018-10-15 onto dev/master. There are a dozen or so merges here but the big one is #859 that touches 108 files. There are no (known) answer changes but parameter documentation files are affected. There is a corresponding branch of MOM6-examples with updated doc files but the parameter docs for you own experiment repositories should be checked.

- Added stress_mag to ice_ocean_boundary_type #825
- Adding OBLIQUE_TAN, OBLIQUE_GRAD options. #826
- Allocate surface tracers on the compute domain. #828
- Capitalize allocated #832
- Avoid NaNs on land in ALE diagnostics #831
- Increase precision of time handling #833
- Fix bug in soliton case. #834
- Reorder loops to address a bug with -O3 using intel compiler version 16.0.3.210 #838
- Added grid rotation angle to the list of available static diagnostics #839
- Fixes reading a scalar on restart when restart files are distributed #840
- Fixes an OOB when processing the restart filename variable #841
- Fix scalar restart variable checksums #843
- Avoid use of %Domain_aux to avoid intermittent MPI sync problem #844
- Fix data_override issue introduced by present(gas_fields_ocn) #845
- Bug fix to compute Rd_dx whenever MEKE is used #858
- Add mol wt to atmos_ocean_fluxes in solo_driver #857
- Dimensional consistency testing of depth units #859

As per usual feedback from @gustavo-marques, @awallcraft, @kshedstrom and @jiandewang is asked for before we accept this PR.

PS> Sorry it took a week. I tried creating this PR three times this week but was interrupted each time. Closing my door seems to have become ineffective.

### CODE REVIEW

**Comment by gustavo-marques** [comment]
I am getting SIGSEGV, see below. I've updated other submodules (e.g., SIS2, icebergs) and did a clean built using dev-master-candidate-2018-10-15. 

```
gmarques@r12i6n34:/glade/work/gmarques/Cheyenne-stats-MOM6-examples> make -f Gitlab/Makefile.run intel_all MEMORY=dynamic_symmetric LOG=
echo build/intel/repro/dynamic_symmetric/coupled_AM2_LM3_SIS/MOM6"("90")" "=>" MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel
build/intel/repro/dynamic_symmetric/coupled_AM2_LM3_SIS/MOM6(90) => MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel
cd MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L && rm -rf Depth_list.nc CPU_stats.intel time_stamp.out ocean.stats.intel RESTART FAIL && mkdir RESTART
cd MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L && tic=$(date +%s) && (OMP_NUM_THREADS=1 KMP_STACKSIZE=512m NC_BLKSZ=1M time mpiexec_mpt -n 90 ../../../build/intel/repro/dynamic_symmetric/coupled_AM2_LM3_SIS/MOM6 > log.intel.out || touch FAIL;) 2>&1 | egrep -v "ing coupler_init| initializ|ing " | sed 's,^,MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: ,' ; toc=$(date +%s) ; echo $(($toc-$tic)) > walltime.intel.out
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: forrtl: severe (174): SIGSEGV, segmentation fault occurred
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: Image              PC                Routine            Line        Source             
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000002CD3241  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000002CD137B  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000002C5C894  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000002C5C6A6  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000002BDF489  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000002BE3B96  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: libpthread-2.19.s  00002AAAAB603870  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               000000000279D895  coupler_types_mod        3776  coupler_types.F90
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               00000000019CC1B8  mom_surface_forci        1518  MOM_surface_forcing.F90
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               000000000045D006  coupler_main_IP_c        1922  coupler_main.F90
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000000453192  MAIN__                    560  coupler_main.F90
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               000000000040531E  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: libc-2.19.so       00002AAAAB832B25  __libc_start_main     Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: MOM6               0000000000405229  Unknown               Unknown  Unknown
MOM6-examples/coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.intel: forrtl: severe (174): SIGSEGV, segmentation fault occurred

```

Currently Loaded Modules:
  1) python/3.6.4   2) ncview/2.1.7   3) ncarenv/1.2   4) intel/17.0.1   5) netcdf/4.6.1   6) ncarcompilers/0.4.1   7) mpt/2.15f

**Comment by jiandewang** [comment]
it works fine on NCEP theia machine. But on NCEP wcoss machine, there are
two minor issues:
(1). src/MOM6/src/ice_shelf/MOM_ice_shelf_dynamics.F90
line 3464 type(ice_shelf_state), intent(in) :: ISS  <-- this need to be
intent(inout)
(2). src/MOM6/src/parameterizations/vertical/MOM_set_viscosity.F90
line 1809   type(ocean_grid_type),   intent(in)    :: G  <-- this need to
be intent(inout)

-- Jiande

**Comment by jiandewang** [comment]
one more intent(inout) issue:
src/MOM6/src/parameterizations/vertical/MOM_CVMix_KPP.F90
867   type(ocean_grid_type),                      intent(in)    :: G
1311   type(ocean_grid_type),                  intent(in)    :: G

-- Jiande

**Comment by adcroft** [comment]
Thanks, @jiandewang . I'm patching 2+3 as you suggested and have a different fix for 1. Testing now and will update PR shortly...

1. I think this is because `ISS%hmask` is passed to a function that has the argument `inout` but in fact `hmask` is not changed so that lower function was incorrect.
2. Yes, annoyingly wherever there is a halo update `G` needs to be `inout`.
3. Similarly, there's a halo update in the smoothing function so `G` has to be `inout` all the way through KPP too.

**Comment by Hallberg-NOAA** [comment]
This PR has problems (will not compile and does not thread properly) with the openMP directives; these issues are addressed for dev/GFDL by https://github.com/NOAA-GFDL/MOM6/pull/866.

**Comment by adcroft** [comment]
I've updated this PR with two commits to address issues found by @jiandewang and @Hallberg-NOAA . Back to you all... @jiandewang, @awallcraft, @kshedstrom, @gustavo-marques 

@gustavo-marques do we need to talk about getting this to work for you?

**Comment by gustavo-marques** [comment]
Thanks @adcroft, after checking MOM6-example recursively and doing a clean build the tests passed. I will re-run the tests now and @alperaltuntas will run the CESM tests.

**Comment by alperaltuntas** [comment]
CESM tests are failing due to a change in the arguments of mech_forcing_diags subroutine (commit 6c4681130b9bec8abffe9372de09649627e15ed9). I will fix the issue, re-run the CESM tests and will send a PR to this candidate if tests pass.

**Comment by jiandewang** [comment]
one more intent issue:
src/MOM6/src/parameterizations/vertical/MOM_geothermal.F90

318   type(ocean_grid_type),   intent(in)    :: G    !< The ocean's grid
structure.

**Comment by alperaltuntas** [comment]
@adcroft et al., PR #871 solves our problem in MCT cap.

@gustavo-marques, The reason we get answer changes is because this candidate does not include the following commit: https://github.com/NCAR/MOM6/commit/6f12f84f0d6d4efe407f4de017913455a604cb65 , which is fine, but something we should be wary of when merging back to dev/ncar.

**Comment by adcroft** [comment]
Two more patches have been made due to @alperaltuntas and @jiandewang . Hopefully no more... ?

**Comment by jiandewang** [comment]
works fine now on NCEP machine.  -- Jiande

**Comment by kshedstrom** [comment]
I approve this PR. Sorry for the delay.

**Pull request merged**
