### PR TITLE
Fix .testing Makefile with WORKSPACE

### PR DESCRIPTION
**Pull request by herrwang0**
When WORKSPACE is specified, the recursive make for target code (for regression tests) does not work properly. This PR fixes this bug.

### CODE REVIEW

**Comment by marshallward** [comment]
Can you describe the problem you are seeing?  I just compiled and ran the test with the current Makefile and following settings:
```
WORKSPACE=$HOME/xxx
DO_REGRESSION_TESTS = true
```
and everything passed.

(Note that `WORKSPACE` has been phased out in favor of `BUILD` and `WORK`, which decouples the build and run directories, but I still don't understand why we need to set `WORKSPACE` in this situation.)

**Comment by herrwang0** [comment]
This is actually a bit tricky.
The problem occurred when I was using the command-line variables. So the variable `WORKSPACE` got passed to target's make call (line 285). The config.mk method does not have this problem, because, well, `TARGET_CODEBASE` directory does not have a config.mk, so `WORKSPACE` is always `.`.

**Comment by marshallward** [comment]
> because, well, `TARGET_CODEBASE` directory does not have a config.mk, so WORKSPACE is always `.`.

OK, that explains the problem.  Thanks for working that out.

This is a very nice solution, and I'd suggest the following small modification:
```
 # Target codebase should use its own build system
 $(BUILD)/target/MOM6: $(BUILD)/target FORCE | $(TARGET_CODEBASE)
-       $(MAKE) -C $(TARGET_CODEBASE)/.testing build/symmetric/MOM6
+       $(MAKE) -C $(TARGET_CODEBASE)/.testing BUILD=build build/symmetric/MOM6
 
 $(BUILD)/target: | $(TARGET_CODEBASE)
+       $(MAKE) -C $(TARGET_CODEBASE)/.testing BUILD=build build/symmetric/
        ln -s $(abspath $(TARGET_CODEBASE))/.testing/build/symmetric $@
```
The first change is to replace `WORKSPACE` with `BUILD`.  This is because we have phased out the `WORKSPACE` macro.

The second change also helps to prevent a dead `build/target` symlink by also build its target directory.

**Comment by herrwang0** [comment]
@marshallward Thanks for the explanation! I modified the PR following the suggestion.

**Comment by marshallward** [comment]
Oops!  My "innocent" suggestion broke the MacOS tests.  I think it's something about GNU vs BSD Make and how end-slashes are handled.

Anyway, let's leave that for another time.  I think just using BUILD in place of WORKSPACE should be good enough.  Sorry for making this more complicated than it needed to be.

**Comment by herrwang0** [comment]
> Oops! My "innocent" suggestion broke the MacOS tests. I think it's something about GNU vs BSD Make and how end-slashes are handled.
> 
> Anyway, let's leave that for another time. I think just using BUILD in place of WORKSPACE should be good enough. Sorry for making this more complicated than it needed to be.

That's good know! Removing the end-slash and using `build/symmetric` seems to work. But I am not sure if that'd be the general solution (my rough understanding is BSD doesn't like end-slashes).  Does `.POSIX:` do anything?

Anyway, I will go ahead without the `mkdir -p` fail-safe.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/25044 :heavy_check_mark:

**Review by marshallward — APPROVED** [review]
Thanks for the additional revision.

`.POSIX:` could help with the problem above, but I don't think the slash usage is consistent enough in the file to get it all working, so probably best to just hold off and do a proper POSIX compatibility check some time in the future.  (Or not... :shrug:)

**Pull request merged**
