### PR TITLE
+Improve documentation in MOM_parameter_doc files

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
This PR consists of a set of changes to improve the logging of modules to
the various MOM_parameter_doc files, including moving the halo size parameters
from the doc.debugging to the doc.all files, and avoiding the logging of
parameters that are specific to unused modules, although they are still being
read to avoid triggering issues if FATAL_UNUSED_PARAMS is true.  The commits
that are including in this PR include:

- NOAA-GFDL/MOM6@f5dfef8 +Do not log parameters from unused modules
- NOAA-GFDL/MOM6@85b784d +Do not log modules to parameter_doc.short files
- NOAA-GFDL/MOM6@cf80f4b +Log modules to parameter_doc.debug files
- NOAA-GFDL/MOM6@5a807f6 +Record halo sizes in MOM_parameter_doc.all files
- NOAA-GFDL/MOM6@b4d3c15 +Add 4 optional args to log_version & doc_module

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
The apparent Travis CI failure here is because a missing diagnostic was added. I do not believe that this should be considered to have actually failed.

**Comment by adcroft** [comment]
Yes it passed. We have no "warning" indicator like we do on gitlab.

**Comment by adcroft** [comment]
Q: Do we still need the MINIMAL_DOCUMENTATON and COMPLETE_DOCUMENTATION parameters?

**Comment by Hallberg-NOAA** [comment]
A: Yes, I think that the MINIMAL_DOCUMENTATION and COMPLETE_DOCUMENTATION parameters are useful for giving users control over what is written.

**Pull request merged**
