### PR TITLE
Converted warning about depth_list to a note

### PR DESCRIPTION
**Pull request by adcroft**
The message that a file is being created was issued as a WARNING when we all agree it should really be a NOTE. Depth_list.nc is read if it is present to avoid recomputing a sorted list, but the absence of the file is not an error and does not warrant a warning.

Changes:
- Changed WARNING to NOTE.
- Removed MOM_mesg from imports since it wasn't being used.

### CODE REVIEW

**Comment by marshallward** [comment]
I'm not even sure that this should be a NOTE.  The file is always created if it doesn't exist, so I'm inclined to interpret it as normal output file.  For comparison, we don't issue notes for the initial creation of `ocean.stats`.

**Review by Hallberg-NOAA — APPROVED** [review]
These changes seem sensible to me.

**Comment by marshallward** [comment]
After discussion with @adcroft, we agreed there is no need for this message anymore and can be removed completely.

**Comment by Hallberg-NOAA** [comment]
I disagree.  In the past, I have found this message to be useful when debugging certain activities related to the diagnosis of the model potential energy.  We can reduce the verbosity level of this message if you would like, but it absolutely should not be removed altogether!

**Comment by marshallward** [comment]
I've reverted the removal.  We'll take this as it is.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/19950 :heavy_check_mark:

**Comment by marshallward** [comment]
The large computational cost of constructing `Depth_list.nc` makes it worth notifying the user, but we discussed the possibility of skipping this notification for initial runs.

But it's not urgent, so we can come back around to this in the future, if we decide to further streamline the model output.

**Pull request merged**
