### PR TITLE
In generic_tracer_source call, perform unit conversion for internal heat only when it is applicable

### PR DESCRIPTION
**Pull request by yichengt900**
This PR is related to another [PR](https://github.com/NOAA-GFDL/ocean_BGC/pull/34) made in the NOAA-GFDL/ocean_BGC repo.

In the past, setting `DO_GEOTHERMAL = True` was necessary for COBALT to function correctly. Failure to enable geothermal heating will lead to segmentation faults if someone turned it off accidently.

We have now made `internal_heat` an [optional argument](https://github.com/NOAA-GFDL/ocean_BGC/blob/048ac6811232c006a6ff2d63f7063911822ba3ef/generic_tracers/generic_COBALT.F90#L6455) in the `generic_COBALT_update_from_source`. The `if(present())` [check](https://github.com/NOAA-GFDL/ocean_BGC/blob/048ac6811232c006a6ff2d63f7063911822ba3ef/generic_tracers/generic_COBALT.F90#L7856) will determine if `internal_heating` is a null pointer. However, in the unit conversion case, the scaling operation `G%US%RZ_to_kg_m2*US%C_to_degC*tv%internal_heat(:,:)` occurs before passing the data to `generic_tracer_source`. This will cause a segmentation fault if `internal_heat` [is null](https://github.com/NOAA-GFDL/MOM6/blob/2c1a9d32fce72828b7091e6f623c0ec20069e637/src/core/MOM.F90#L2811-L28135).

This PR (proposed by @andrew-c-ross originally) fixes this issue by omitting this argument if `internal_heat` is not associated.

### CODE REVIEW

**Review by Hallberg-NOAA — APPROVED** [review]
I agree that these changes correct the problem that is being described.

  In the longer, term, it might be even better if we could arrange to (optionally) pass a MOM `unit_scale_type` argument into `generic_tracer_sources()`.  This would have the benefits of limiting the code-duplication in MOM_generic_tracer.F90 while also allowing us to propagate the dimensional consistency testing for physical variables into the generic tracer code.

**Comment by adcroft** [comment]
@yichengt900 Can you check "Allow edits and access to secrets by maintainers" at the bottom of the right hand column (also when you submit a PR)? Our branch rules block merges for out of date code w.r.t. dev/gfdl. That option allows us to update the branch.

**Comment by yichengt900** [comment]
Thanks, @adcroft. I think Marshall pointed it out the same issue, and it appears that the option `Allow edits and access to secrets by maintainers` does not show up when merging an organization fork (weird). I have manually merged the recent updates into my branch.

**Comment by adcroft** [comment]
Testing at https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/24226

**Pull request merged**
