### PR TITLE
New option to use a grid index convention for spatially-varying diagn…

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
New option to use a grid index convention for spatially-varying diagnostics.

   USE_GRID_SPACE_DIAGNOSTIC_AXES=True enables this option.

### CODE REVIEW

**Comment by adcroft** [comment]
Thank you! So simple a change. I suggest turning this on in just one of the TCs so the coverage is there.

**Comment by kshedstrom** [comment]
Thanks, Matt! You save yourself having to explain the old way to others.

**Comment by kshedstrom** [comment]
I had to try this out because my Fram Strait crosses the dateline in xh space and FMS didn't like it. It's finally running!

**Comment by marshallward** [comment]
This is passing (despite the zombie Travis/GitHub test).

**Pull request merged**
