### PR TITLE
Add double diffusion (old method and via CVMix) + additional updates

### PR DESCRIPTION
**Pull request by gustavo-marques**
This PR adds the following capabilities:

### Double-diffusion
- A new module `MOM_CVMix_ddiff` for computing double-diffusion using CVMix has been added. This method can be selected via the input parameter `USE_CVMIX_DDIFF`. At this moment, diffusivities from `MOM_CVMix_ddiff` **are not** being used. This step will be added as we re-structure the module `MOM_diabatic_driver`;
- The old method for computing double-diffusion is kept for legacy purposes.  

### "Legacy" diabatic_driver
- A new input parameter has been added `USE_LEGACY_DIABATIC_DRIVER`. If true, the model will
use a legacy version of the diabatic driver (module `MOM_legacy_diabatic_driver`). This is
temporary and is needed to avoid change in answers while `MOM_diabatic_driver` is been
restructured;
- Code related to the "layer mode" has been deleted from subroutine diabatic. 

###  KPP BLD smoothing
- The i,j loop to compute (1) KPP Boundary layer depth and (2) diffusivities is divided into two loops such that BLD is computed over the entire grid before diffusivities get computed. This is because BLD of neighboring cells is necessary to apply smoothing. The new loop containing KPP BLD computation is placed in a new subroutine called `KPP_compute_BLD`.
- A new logical called `smoothBLD` now controls whether a Laplacian Filter is to be applied on BLD after BLD is computed by KPL and before diffusivities are computed.
- A new subroutine, `KPP_smooth_BLD`, is added that implements a 1-1-4-1-1 Laplacian filter one time on BLD to reduce any horizontal two-grid-point noise.

### Schmittner tidal mixing
- In tidal mixing module, the capability of reading 3d tidal energy dissipation data (in ER03 format) is added as an option.
- CVMix Schmittner tidal mixing scheme is added as an option and all the necessary CVMix subroutine calls are added.
- Diagnostics are added for Schmittner tidal mixing.

### Additional updates
- Option to smooth Ri using a 1-2-1 filter in `MOM_cvmix_shear`. This is done via an input parameter `SMOOTH_RI`;

- Option to diagnose total vertical viscosity at u and v points. Variables `Kv_u` and `Kv_u` in available.diags;

- Option to add the contribution of 'slow' varying interior processes (i.e., tidal + background + convection) to the total vertical viscosity. This is done via an input parameter `ADD_KV_SLOW`.  The purpose of this flag is to be able to recover previous answers and it will likely be removed in the future since this option should always be true. The vertical viscosity from slow varying processes is updated every thermodynamic time-step, while the model solves a fully implicit system for the vertical viscosity of momentum every dynamic (i.e., barotropic) time-step. Since, in most applications, the dynamic time-step is << than the thermodynamic time-step, contributions from slow varying processes are kept constant until the next thermodynamic update. 

This PR does not change answers (only Intel was tested) recorded for dev-master-candidate-2018-05-15.

### CODE REVIEW

**Comment by StephenGriffies** [comment]
Perhaps you should rename 

MOM_KPP.F90 

to 

MOM_CVMix_KPP.F90 

to correspond to the other modules with the CVMix name?

**Comment by gustavo-marques** [comment]
I agree. For consistency with other CVMix-related modules, MOM_KPP.F90 should be renamed to MOM_CVMix_KPP.F90. I'll do that on dev/ncar and it will be pushed to dev/master on a subsequent pull request. Thanks @StephenGriffies.

**Comment by gustavo-marques** [comment]
I just realized that this PR does not pass the double-diffusion (via CVMix) test in MOM6-cases. I am going to close it for now and re-open it once this is fixed (hopefully tomorrow morning).

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/4454

**Comment by gustavo-marques** [comment]
@adcroft This PR is ready to be evaluated.

**Comment by adcroft** [comment]
Apart from known issues that are already fixed on dev/gfdl this is passing our tests.

Note that there are conflicts with dev/gfdl: there is a sequence of reverts and cherry-picks needed on dev/gfdl that I will line up and submit back to dev/master once this PR is accepted.

@Hallberg-NOAA Is there anything in this PR that needs addressing?

**Comment by Hallberg-NOAA** [comment]
Overall I  concur with these changes.

   There are a few typos in some of the comments (as there often are), and there is at least one place where back-to-back pass_var calls could be combined into a group pass for greater efficiency by avoiding an extra synchronization call.  We will take care of fixing these minor issues in a later PR.

**Pull request merged**
