### PR TITLE
*Non-Boussinesq refactoring of brine plumes

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
Revised the recently added brine-plume code to avoid using a vertical sum and to use tv%SpV_avg to determine the brine plume mixing thickness instead of GV%Z_to_H when in non-Boussinesq mode. Several internal brine plume expressions now work in units of H instead of Z, and a total of 5 unit conversion factors were eliminated. This will change certain non-Boussinesq calculations to avoid any dependency on the Boussinesq reference density, but some Boussinesq answers may also be changed and made more robust by avoiding the answer-indeterminate sum() function.

### CODE REVIEW

**Comment by marshallward** [comment]
@kshedstrom Would you mind reviewing this?

**Review by kshedstrom — APPROVED** [review]
I approve this PR. It doesn't change answers in Boussinesq mode.

**Review by marshallward — APPROVED** [review]
OBO @kshedstrom

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/21261 :heavy_check_mark:

**Pull request merged**
