### PR TITLE
[WIP] Please ignore this! An alternate fix to class(*) issues with FMS 2022-01

### PR DESCRIPTION
**Pull request by nikizadehgfdl**
- This update is an alternate to PR#66 to fix the issues with passing
read arguments to subroutines receiving class(*)
- This tries to show that there are no inherent issues with passing a
  real and receiving it as class(*).
  Rather the root cause of the issues is some of these arguments are
  optional and are being passed to FMS even thought they are not present!
  Then they are trapped in FMS diag_manager inside a SELECT TYPE statement
  and the compiler is not smart enough to know that they are absent and bombs.

### CODE REVIEW

**Comment by marshallward** [comment]
@nikizadehgfdl I tested the current `dev/gfdl` with `FMS 2022.01-beta1` and there were no compile-time errors, or runtime errors in the `.testing` suite.

Is this a runtime error?  Do I need to use a more complicated test, e.g. the production regression suite?  Or a different FMS build?

**Comment by jiandewang** [comment]
@marshallward @nikizadehgfdl Thanks for this information, we will do corresponding testing in UFS.
@nikizadehgfdl can you also make corresponding change in FMS2/infra code ?

**Comment by nikizadehgfdl** [comment]
@marshallward, this is to avoid runtime errors and you need tests that have extensive diag_table, like OMIP,CM, ESM. If diag_table has no diagnostics that require mask or weight you won't run into any problem.

**Comment by nikizadehgfdl** [comment]
@jiandewang I updated infra/FMS2 the same way. My tests passed with FMS2022.01-beta1 (mixed-mode tag of FMS).

**Comment by MinsukJi-NOAA** [comment]
@jiandewang
I used your branch https://github.com/jiandewang/MOM6/tree/test/FMS-cherrypick-Niki to test the latest UFS weather model.
All regression tests passed on Hera and WCOSS Dell: https://github.com/ufs-community/ufs-weather-model/issues/1036

**Comment by jiandewang** [comment]
> @jiandewang I updated infra/FMS2 the same way. My tests passed with FMS2022.01-beta1 (mixed-mode tag of FMS).

@nikizadehgfdl thanks for the heads up and sorry for my late reply as I was out of town in the past week. We will do more testing and get back to you and Marshall.

**Comment by MinsukJi-NOAA** [comment]
@jiandewang 
Regression tests on platforms Hera, WCOSS, and Gaea all passed using the latest changes in your MOM6 branch: https://github.com/jiandewang/MOM6/tree/test/FMS-cherrypick-Niki. These include intel, gnu, and debug tests.
Also, the RT's used the FMS2 infra by modifying the mom6_files.cmake file in the UFS weather model repository.

**Comment by jiandewang** [comment]
> @jiandewang Regression tests on platforms Hera, WCOSS, and Gaea all passed using the latest changes in your MOM6 branch: https://github.com/jiandewang/MOM6/tree/test/FMS-cherrypick-Niki. These include intel, gnu, and debug tests. Also, the RT's used the FMS2 infra by modifying the mom6_files.cmake file in the UFS weather model repository.

@MinsukJi-NOAA can you provide information on which version of FMS library code being used in your test ?

**Comment by MinsukJi-NOAA** [comment]
> > @jiandewang Regression tests on platforms Hera, WCOSS, and Gaea all passed using the latest changes in your MOM6 branch: https://github.com/jiandewang/MOM6/tree/test/FMS-cherrypick-Niki. These include intel, gnu, and debug tests. Also, the RT's used the FMS2 infra by modifying the mom6_files.cmake file in the UFS weather model repository.
> 
> @MinsukJi-NOAA can you provide information on which version of FMS library code being used in your test ?

FMS2 is being used. See [here](https://github.com/MinsukJi-NOAA/ufs-weather-model/blob/555c05811e96c1d534d0b9ca966607dbbeb1bff7/MOM6-interface/mom6_files.cmake#L264)

**Comment by marshallward** [comment]
This PR will be sent directly to EMC, which is actively testing the FMS mixed precision support.

https://github.com/NOAA-EMC/MOM6/pull/88

We will eventually take this in via mom-ocean/MOM6 after EMC submits a PR in the future.

**Pull request closed without merging**
