### PR TITLE
OBC: dz_src rescaling fixed in N-S segments

### PR DESCRIPTION
**Pull request by marshallward**
When reading an OBC segment field from a file which is not V or DVDX,
the field is remapped from the input file levels, set by dz_src, to the
model levels, set by h, via remapping_core_h.

When remapping on east-west segments, dz_src is rescaled to match the
total width of h, saved in variable scl_fac.  But this factor was not
being applied on north-south segments.  This was causing variations in
rotated OBC simulations.

This patch resovles the asymmetry by applying the rescaling along the
N-S segments.

### CODE REVIEW

**Comment by marshallward** [comment]
Gaea regression test: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/9925

**Comment by raphaeldussin** [comment]
FYI There was an issue with the rescaling of dz_src to total depth that @MJHarrison-GFDL and I found several months ago. The data in the open boundary condition file can be deeper than the model bottom depth. In the bugged code, the data thicknesses dz_src where rescaled to the bottom depth, which was basically compressing 6000 meters of ocean into 3000 or less, lifting the thermocline,... and giving bad results.

Is it something related that is not passing the rotation test?

**Comment by marshallward** [comment]
I can believe that, it seems like it could have some unintended effects like you describe.

My understanding from talking with others here is that it's primarily done to conserve volume.

Forgot to mention that I hope @kshedstrom and @MJHarrison-GFDL get a chance to review this, to make sure I'm doing the right thing here.

**Comment by raphaeldussin** [comment]
the solution that @MJHarrison-GFDL implemented was to drop all dz_src below the ocean bottom, which is the right thing to do since some of the data in the obc files are extrapolated to the last level and those values have no sense.

**Comment by kshedstrom** [comment]
I agree that we should do the same thing NS as EW in terms of the scaling and I agree with @raphaeldussin that we should drop values below our sea bottom.

If the fields other than tangential velocity have this scaling, what about tangential velocity? That too should be dropped below the sea bottom.

This may be a necessary fix, but it is not sufficient to get my rotated dumbbells in line.

**Comment by marshallward** [comment]
Gaea regression has passed.

Same here @kshedstrom I am still fighting additional problems, but my answers are finally starting to converge.

**Comment by MJHarrison-GFDL** [comment]
Agreed. We should rescaling the thicknesses in both directions, so this PR is correct.

The following drops the bottom cells below bathymetry and makes the input grid consistent with
a static grid:

https://github.com/NOAA-GFDL/MOM6/blob/dev/gfdl/src/core/MOM_open_boundary.F90#L3645

Subsequent rescaling fits to dynamic thicknesses.

**Comment by kshedstrom** [comment]
Why is there not a scl_fac term in the tangential velocity or its gradient?

**Comment by MJHarrison-GFDL** [comment]
I believe the answer is that the q values are not used for transport, so it's not an issue.

**Comment by marshallward** [comment]
I've updated this PR with another change.  In `PPM_reconstruction_y`, the OBC control flag was using `OBC%open_u_BCs_exist_globally` rather than the `v` equivalent.

After making this change, I now get reproducible results in tc4 OBC test that @MJHarrison-GFDL prepared for me.

**Comment by marshallward** [comment]
Resumitted Gaea regression test: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/9941

**Comment by kshedstrom** [comment]
I approve the update - getting much closer!

**Pull request merged**
