### PR TITLE
Updates to discontinuous neutral diffusion

### PR DESCRIPTION
**Pull request by ashao**
This PR encapsulates a number of changes to the discontinuous version of the neutral diffusion code

1) Based on discussions with @adcroft, the behavior of the neutral surface finding algorithm needed to be changed to correctly to deal with scenarios where water columns are statically unstable (either in part or in whole). 

2) Fixes for the iterative procedure for finding a neutral position within a layer:
- Convergence is achieved if the difference in density is negative (from the perspective of the searched column). This ensures that the logic governing whether to connect within a given layer behaves correctly without relying on careful evaluation of tolerances. In the event that the algorithm quits for any other reason, the function outputs the position corresponding to the iteration with the smallest negative difference in delta rho.
- A bisection step is now taken if the derivative of density difference evaluates to zero. 

3) MOM_neutral_diffusion.F90 was pretty long for a single file. Many routines were put into a MOM_neutral_diffusion_aux.F90 and some runtime parameters added to control structures at both the main and auxilliary neutral diffusion modules. 

4) Two new diagnostics uheff_2d and vheff_2d representing the sum of the effective thickness of the neutral diffusion sublayers at u and v points respectively.

This new code behaves as expected in various configurations of the tracer mixing test cases with linear and nonlinear equations of state using PLM, PPM_H4, and PPM_IH4 reconstructions. The algorithm also runs stably within OM4_05 for at least 30 days.

Note: This changes available_diags and MOM_parameter_doc for any cases where the neutral diffusion is used.

### CODE REVIEW

**Comment by ashao** [comment]
This is ready for a pipeline whenever convenient

**Comment by Hallberg-NOAA** [comment]
Thank you, @ashao , for this contribution.  It does run correctly through our test cases, but there are two things that I think need to be fixed before this is merged into the main branch.

1. On line 447 of the new version of MOM_neutral_diffusion.F90, there is a reference to CS%stable_cell(i,j,k) that is outside of any i-loop, so just from visual inspection I am pretty sure that the logic here is wrong.  Please fix this or add a comment explaining why this is actually correct.

2. On lines 522 and 523, there is a rescaling of uhEff and vhEff by an array syntax division by GV%H_to_Pe. First, please do not use array syntax to do math on full arrays - this can cause trouble if there are undefined values in halo regions. Second, division is about 20 times more expensive than multiplication, so please replace division by a constant with multiplication by its reciprocal. Most optimizing compilers would do this automatically, but writing the code this way leads to answers that differ unnecessarily between optimized and non-optimized versions of the code, which can interfere with debugging.

  Another issue that we might want to discuss is whether it is advisable from the standpoint of performance to extract the numerous kernel-level routines into a separate module, MOM_neutral_diffusion_aux. In the past, this separation into two modules would have inhibited the in-lining of these simple routines, with significant performance implications, but I do not know whether this is still the case.

**Comment by ashao** [comment]
Thank you @Hallberg-NOAA for the code review and for the helpful suggestions. I will push a new commit once I am confident that the fixes do not change the algorithm. 

1. You are indeed correct. This logic was a holdover from before the updates to mark_unstable_cells. Thankfully this oversight on my part does not actually affect how the algorithm works because at the top of the routine stable_cell is initialized to true and is not modified until later in the routine. This logic has been removed
2. This has been changed to explicit loops using a new variable. It also gave me a chance to comment why the conversion is not needed for the discontinuous reconstructions

To your last point: It is clear from a compiler optimization standpoint that having all the routines in the same source file helps make the inlining easier, but I decided to break it into two separate files because I thought that MOM_neutral_diffusion.F90 was getting rather long. Most of the routines that I moved to MOM_neutral_diffusion_aux.F90 are logic-heavy and work on relatively small arrays (none of them full 3D). As such I would speculate that the usual benefits of inlining (not having to pass to/from stack) are small relative to the overall computational cost. That being said, there is no practical reason (other than code organization) to not include them all in the same file. I'll move some functions back into the main module and check timings to see if it might be worth it.

**Comment by adcroft** [comment]
Good news is the mods run and reproduce across layout and restarts but it is changing answers for 5 test cases.
image

```
cd _gnu ; md5sum -c ../gnu.md5
coupled_AM2_LM3_SIS/CM2G63L/ocean.stats.gnu: OK
coupled_AM2_LM3_SIS2/AM2_SIS2_MOM6i_1deg/ocean.stats.gnu: OK
coupled_AM2_LM3_SIS2/Concurrent_ice_1deg/ocean.stats.gnu: OK
ice_ocean_SIS2/Baltic/ocean.stats.gnu: OK
ice_ocean_SIS2/OM4_025/ocean.stats.gnu: OK
ice_ocean_SIS2/SIS2/ocean.stats.gnu: OK
ice_ocean_SIS2/OM4_05/ocean.stats.gnu: FAILED
ice_ocean_SIS2/SIS2_bergs_cgrid/ocean.stats.gnu: OK
ice_ocean_SIS2/Baltic_ALE_z_offline_tracers/ocean.stats.gnu: OK
ice_ocean_SIS2/SIS2_cgrid/ocean.stats.gnu: OK
land_ice_ocean_LM3_SIS2/OM_360x320_C180/ocean.stats.gnu: OK
ocean_only/DOME/ocean.stats.gnu: OK
ocean_only/global_ALE/z/ocean.stats.gnu: FAILED
ocean_only/global_ALE/hycom/ocean.stats.gnu: FAILED
ocean_only/global_ALE/layer/ocean.stats.gnu: OK
ocean_only/adjustment2d/rho/ocean.stats.gnu: OK
ocean_only/adjustment2d/z/ocean.stats.gnu: OK
ocean_only/adjustment2d/layer/ocean.stats.gnu: OK
ocean_only/external_gwave/ocean.stats.gnu: OK
ocean_only/SCM_idealized_hurricane/ocean.stats.gnu: OK
ocean_only/tracer_mixing/rho/ocean.stats.gnu: FAILED
ocean_only/tracer_mixing/z/ocean.stats.gnu: FAILED
ocean_only/circle_obcs/ocean.stats.gnu: OK
ocean_only/resting/z/ocean.stats.gnu: OK
ocean_only/resting/layer/ocean.stats.gnu: OK
ocean_only/nonBous_global/ocean.stats.gnu: OK
ocean_only/single_column/BML/ocean.stats.gnu: OK
ocean_only/single_column/KPP/ocean.stats.gnu: OK
ocean_only/single_column/EPBL/ocean.stats.gnu: OK
ocean_only/lock_exchange/ocean.stats.gnu: OK
ocean_only/benchmark/ocean.stats.gnu: OK
ocean_only/unit_tests/ocean.stats.gnu: OK
ocean_only/flow_downslope/rho/ocean.stats.gnu: OK
ocean_only/flow_downslope/z/ocean.stats.gnu: OK
ocean_only/flow_downslope/layer/ocean.stats.gnu: OK
ocean_only/flow_downslope/sigma/ocean.stats.gnu: OK
ocean_only/double_gyre/ocean.stats.gnu: OK
ocean_only/sloshing/rho/ocean.stats.gnu: OK
ocean_only/sloshing/z/ocean.stats.gnu: OK
ocean_only/sloshing/layer/ocean.stats.gnu: OK
ocean_only/mixed_layer_restrat_2d/ocean.stats.gnu: OK
ocean_only/torus_advection_test/ocean.stats.gnu: OK
ocean_only/seamount/rho/ocean.stats.gnu: OK
ocean_only/seamount/z/ocean.stats.gnu: OK
ocean_only/seamount/layer/ocean.stats.gnu: OK
ocean_only/seamount/sigma/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/wind_only/BML/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/wind_only/KPP/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/wind_only/EPBL/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/mech_only/BML/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/mech_only/KPP/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/mech_only/EPBL/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/cooling_only/BML/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/cooling_only/KPP/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/cooling_only/EPBL/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/skin_warming_wind/BML/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/skin_warming_wind/KPP/ocean.stats.gnu: OK
ocean_only/CVmix_SCM_tests/skin_warming_wind/EPBL/ocean.stats.gnu: OK
ocean_only/Phillips_2layer/ocean.stats.gnu: OK
md5sum: WARNING: 5 computed checksums did NOT match
```

**Comment by ashao** [comment]
Hrmm interesting. I'll hunt this down.

**Comment by ashao** [comment]
I tracked this down to the changing the division of u(v)hEff by GV%H_to_pa to a multiplication by its precomputed reciprocal as suggested by @Hallberg-NOAA and implemented in 8f4af3d9ef927dc4b99d2a44f32a1e0a3ca5c2c3. It is not from the changing the array arithmetic to explicit loops. Should I revert this change or do you want to go ahead and update answers?

**Comment by adcroft** [comment]
I've confirmed that replacing `* pa_to_H` with `/ G%H_to_pa` in 8f4af3d9ef927 recovers the original answers. All affected stats only changed in the lower bits .

**Pull request merged**
