### PR TITLE
Use flush function instead of subroutine/extension

### LINKED ISSUE #1263: Convert from flush subroutine to intrinsic statement
As mentioned in https://github.com/NOAA-GFDL/MOM6/pull/1165#issuecomment-733916634, we (the GEOS developers) found that when using Intel Fortran on macOS that, for some reason, Intel was getting confused by `call FLUSH()` calls. This is probably because the `call FLUSH()` subroutine is a Fortran extension. So we've been internally in GEOS and in our forks, converting all the `call FLUSH()` to use the Fortran Standard `FLUSH()` intrinsic (which I think every good Fortran compiler now should support) and that seems to be helping.

### PR DESCRIPTION
**Pull request by mathomp4**
This fixes #1263. It converts the `call FLUSH()` in MOM6 to be `flush()`

### CODE REVIEW

**Comment by mathomp4** [comment]
Huh. I am not sure how I broke Doxygen. I'm kind of impressed that this could. 😄

**Comment by marshallward** [comment]
@mathomp4 That was some sort of Ubuntu packaging issue (libpoppler security problem?).  Anyway seems fixed now.

**Comment by marshallward** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11621

**Comment by marshallward** [comment]
Thanks, this does not appear to be causing any problems so I will merge it.

**Review by marshallward — APPROVED** [review]

**Pull request merged**
