### PR TITLE
Travis test suite expansion

### PR DESCRIPTION
**Pull request by marshallward**
Travis test suite expansion

This patch extends the current test suite to report code coverage and
includes the following tests:

* Regression testing (for a GitHub PR)
* Symmetric/nonsymmetric grids
* Layouts for 1 and 2 domains
* Restart resubmission
* DEBUG/REPRO builds
* NaN initialization of allocated arrays
* Dimensional scaling (2^11)

The test uses four build configurations:

* Symmetric grids
* Asymmetric grids
* REPRO build
* A "target" build for PR merges, as a regression test

A test will pass if the "ocean.stats" file is unchanged when compared to
the symmetric DEBUG build.

Comparisons of the diagnostic checksums ("chksum_diag") are included
but the results are only reported and are not treated as a
fail-condition.

Four experiments are currently supported, currently based on the
MOM6-examples repo:

* tc0: unit_tests
* tc1: A low-resolution configuration of benchmark
* tc2: An ALE-based config of benchmark
* tc3: A shortened simulation of circle_obcs

Coverage reports are generated using "gcov" and are reported to
"codecov.io".

The build Makefile (.testing/Makefile) is usable at command line and
does not require a Travis VM session, although there are some
potentially volatile dependencies on git which should probably be
explored before distributing it for general use.

It is expected that the tests will be expanded (e.g. repeat using
MOM_parameter_doc output) as well as the number of experiments.

Other notes:
- Includes an independent build of FMS
- Real-number inequality warnings are disabled

### CODE REVIEW

**Comment by marshallward** [comment]
Note this is also a test to see if the PR triggers the regression test within Travis, which I haven't confirmed yet.

**Comment by marshallward** [comment]
Fixed a bug in the Makefile and one of the Travis environment variables.  This appears to be working now.

It's ready for feedback now if anyone gets a chance.

**Comment by marshallward** [comment]
BTW there is no code coverage reporting here, we may need to define a token or something from NOAA-GFDL codecov.io.

**Comment by marshallward** [comment]
This now works for PRs but is failing for pushes, since Travis checks out the code on a detached HEAD, and the scripts think its branch name is `HEAD`.  Pushing a change now that seems to work.

**Comment by raphaeldussin** [comment]
@marshallward isn't it bad practice to push to "master" directly?

**Comment by marshallward** [comment]
@raphaeldussin This is just for the action of a push, which triggers a Travis build, not a push to `master` or any particular build.

I've tested the latest change, and it successfully runs for both Travis pushes and Travis PRs, so it's ready for review.

**Pull request merged**
