### PR TITLE
Conditionally deallocate spherical harmonic fields

### PR DESCRIPTION
**Pull request by marshallward**
This patch moves the local `use_tides` flag of the split RK2 solver, which tracks the TIDES parameter, into the RK2 control structure (CS), and uses it to conditionally call `tidal_forcing_end().

The `tidal_forcing_init()` function conditionally allocates the spherical harmonic fields, but `tidal_forcing_end()` is always called, which will in turn always attempt to deallocate the fields.  In some compilers, under certain levels of debugging, this can raise a runtime error.

### CODE REVIEW

**Comment by herrwang0** [comment]
This looks good to me!

**Review by Hallberg-NOAA — APPROVED** [review]
These changes should successfully fix the problems that they are intended address. This PR should be adopted once it has passed the pipeline testing.

**Comment by marshallward** [comment]
I would like @jiandewang to review this before it is merged.

**Comment by jiandewang** [comment]
@marshallward works fine in UFS now, thanks

**Comment by marshallward** [comment]
Gaea regression (against dev/gfdl stats): https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/17386 :heavy_check_mark:

**Comment by marshallward** [comment]
This has been tested and approved, so I will merge this one.

**Pull request merged**
