### PR TITLE
+Add infrastructure interfaces needed by SIS2

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
This PR adds some well-documented wrappers for the infrastructure calls that
are needed by SIS2, but are not used directly by MOM6.  SIS2 reuses the MOM6
infrastructure code, with this change all of the SIS2 infrastructure calls to
FMS (apart from restarts) are now channeled through the MOM6 framework or
config_src/infra directories.  ALl answers are bitwise identical, but there are
some publicly visible interfaces that are new to MOM6 (although are not new in
that they replicate FMS interfaces).  The commits in this PR include:

- NOAA-GFDL/MOM6@3c1cb2efd +Add MOM_domains interfaces needed by SIS2
- NOAA-GFDL/MOM6@cfa59aab1 +Add coupler_types interfaces needed by SIS2

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
This PR has passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/12410.

**Comment by Hallberg-NOAA** [comment]
This PR has passed pipeline testing again at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/12418.

**Comment by klindsay28** [comment]
There are multiple occurrences of comments of the form
`Copy all elements of the data in of one ... into another.`
where `...` is one or two types. Should that be
`data in a ... into another.` when `...` is one type, and
`data in one of ... into another.` when `...` is two types?

**Comment by Hallberg-NOAA** [comment]
Thanks for the suggestions, @klindsay28!  I just pushed an update that should clarify the problematic descriptions you highlighted.

**Review by marshallward — APPROVED** [review]

**Pull request merged**
