### PR TITLE
MOM6: +Miscellaneous code cleanup

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
This PR includes a number of minor changes to clean up the MOM6 code, 
including corrections to comments, removing an unnecessary halo update
rescaling of internal diagnostic calculations, and refactoring of the 
find_interfaces code to avoid lots of unnecessary copies and to match the code
style used elsewhere in the MOM6 code.  There are no changes to solutions,   
diagnostics, or output files.  The commits in this PR include:

- NOAA-GFDL/MOM6@7a7488f Removed an unneeded halo update
- NOAA-GFDL/MOM6@5b76e07 +Converted find_interfaces from a function to a subroutine
- NOAA-GFDL/MOM6@43ba3bc +Rescaled density derivatives in full_convection
- NOAA-GFDL/MOM6@2c2cf56 Rescaled diagnostic calculations
- NOAA-GFDL/MOM6@6760d1e Corrected documented units in comments

### CODE REVIEW

**Comment by Hallberg-NOAA** [comment]
This PR is being tested with https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/10041.

Please note that there are no conflicts between the four recent PRs, #1074, #1075, #1076, and #1077, and they can be handled in any order.  Three of these should be automatically verified and just involve the push of a green button, while the fourth ( #1074) does require updates to the available_diags files.

**Comment by marshallward** [comment]
I trust you that these are non-overlapping, but I also think that we should follow the process and re-submit to Gaea after each PR merge, and might as well start at the beginning of the queue.

My Lustre issue appears to have been solved, so I will work through them now.

**Comment by adcroft** [comment]
I would not trust that multiple PRs are non-overlapping. I always re-submit the gitlab pipeline after a previous PR has changed the code.

**Comment by marshallward** [comment]
Gaea regression test: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/10044

**Pull request merged**
