### PR TITLE
Astronomical longitudes bugfix

### PR DESCRIPTION
**Pull request by ezaron**
[This is a revision of PR #363 which removes an unnecessary change to tc2/MOM_tc_variant in order to pass the regression test checks.]

This PR corrects an error in the astronomical longitudes computed in src/parameterizations/lateral/MOM_tidal_forcing.F90 and used in all tidal applications. The formulation used in dev/gfdl contains an error related to an error in the cited source of the astronomical longitudes, Kowalik and Luick. The formulas in Kowalik and Luick use an incorrect value for the number of days in a Julian Century, namely, 36526 days. When the formulas were copied into dev/gfdl, the programmer noticed this error in Kowalik and Luick and corrected it to the value, 36525 days. Unfortunately, Kowalik and Luick apparently used the incorrect value in their derivation of the formulas for the astronomical longitudes.

The dev/gfdl bug would affect all results which intend to resolve the phase of the tides on a specific date. The error is equivalent to a timing offset of 1-day per century from 1900 (i.e., approximately a timing error of 1.2-day during the current year, 2023). The PR fixes the error and reduces it to less than 30 seconds when compared to independently tabulated values of the astronomical longitudes, a completely negligible error.

The check-ins in my JDbugfix branch sequentially demonstrate the error and allow it to be verified using independent sources. The check-ins consist of two "steps". The first step in the bugfix involves printing out the incorrect values of the longitudes. The second step implements the bugfix and prints out the correct values. The final check-in of this PR turns off the print statement but keeps the bugfix in the code.

### CODE REVIEW

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
Thank you @ezaron for tracking down and correcting this bug.  I am convinced that this correction is the right thing to do, but I would also appreciate the input from @andrew-c-ross, who who originally added this code to MOM6 and noted this potential problem in a comment.

  There is, however, a procedural issue with how we handle answer changing bug-fixes like this to prevent anyone's answers with MOM6 from changing unexpectedly, and to allow for the recreation of previous solutions.  We always add a bug fix with a run-time parameter (here it would be something like ASTRO_TIDE_LON_BUG, with True being to keep the previous answer - see https://github.com/NOAA-GFDL/MOM6/issues/237).   This new option would usually be stored in a control structure for use at run time, but in this case it might make sense for this flag to be an optional logical argument to `astro_longitudes_init()` that is stored in the calling routine's control structure.

  To help manage the answer-change process in MOM6 and eventually clean up old, incorrect and unused code, we take the following steps:

1. Introduce the new bug-fix flag with a default value that reproduces the existing (buggy) solution.  This causes it to be logged in any configurations that use it.
2. At least 1 cycle of PRs to main later, change the default to correct the bug.  This might change answers in some cases, but because the parameter is being logged, a diff of the MOM_parameter_doc.short files quickly reveals the parameter setting that are needed to reproduce the desired answers.
3. At least a year after the default is changed, a run-time parameter may be formally obsoleted  (removed from the code, but with a warning if it appears in any input files) by community-wide consensus.
4. At least a year after the parameter has been obsoleted, it may be removed from the obsolete parameter list by community consensus.

  The exceptions to this whole procedure would be if this is fix to a bug in code that has been added so recently that we have confidence that it has never been exercised in any scientifically important configuration by any MOM6 user anywhere, or if it is correcting an obvious inconsistency (e.g., failing reproducibility across layouts) such that there is not previous valid solution to preserve.  Given that this code has been here for about 3 years, I do not think that either exception applies.

  If you would like, @ezaron, I would be happy to work with you on adding the run-time flags to make this correction in a way that will gracefully bring other MOM6 users along.

**Comment by ezaron** [comment]
Thank you, @Hallberg-NOAA for taking a look at this. The process you describe sounds very good. The only caller of `astro_longitudes_init` is `tidal_forcing_init`, and that latter routine also reads the tide-related parameters out of MOM_input. The source code changes described should be comprehensible and isolated to the `MOM_tidal_forcing.F90` file.
I'll update the PR in a few days with your suggestions.

**Comment by ezaron** [comment]
Aha! Thanks a lot, @andrew-c-ross . I did not realize there were options for using different calendar systems, and the Julian calendar appears to be the default. I inserted "calendar=gregorian" into my input.nml and I can reproduce your results.
I'll close this PR next week unless there are other comments in the meantime.

**Comment by Hallberg-NOAA** [comment]
Thank you, @andrew-c-ross and @ezaron, for this productive conversation, which identified this as a problem with the calendar settings in the input.nml file.  I am going to close this PR for now, but it could be reopened if these changes are still needed after further consideration.

**Pull request closed without merging**
