### PR TITLE
dev/master candidate 2019-07-08

### PR DESCRIPTION
**Pull request by adcroft**
This is the PR onto dev/master discussed in the dev call today. It looks big (144 commits, 139 files changed) but is not conceptually big. The main changes are:
- many of bug fixes for diagnostics, particularly in symmetric-memory mode from @marshallward 
- updates for MEKE + backscatter from @MFJansen 
- new experiment capability from @ElizabethYankovsky 
- more dimensional checking from @Hallberg-NOAA 
- fixes for static memory compilation and QG Leith arguments from @adcroft 

MOM6-examples has a similarly named branch/PR (NOAA-GFDL/MOM6-examples#276) for reference.

As usual, @awallcraft, @kshedstrom, @jiandewang, @gustavo-marques please check.

### CODE REVIEW

**Comment by kshedstrom** [comment]
I approve this PR.

**Comment by awallcraft** [comment]
I approve this PR.

**Comment by jiandewang** [comment]
works fine in EMC Unified Coupled System

**Comment by gustavo-marques** [comment]
Apologies for holding this PR. Unfortunately, Cheyenne is not working... Once it's back, I will evaluate the PR ASAP.

**Comment by gustavo-marques** [comment]
I approve this PR (b4b G- and C-compsets for tx0.61).

**Comment by adcroft** [comment]
We have green lights across the board - I'll make the merge...

**Pull request merged**
