### PR TITLE
Add save_MOM6_internal_state subroutine to MOM.F90 and call during restart

### PR DESCRIPTION
**Pull request by cspencerjones**
As described in issue #372, I would like to be able to create restart files that contain information about the particle location. These files should be written at the same time as other restart files. I cannot add these calls directly to the driver, because the driver does not have information about the particle location. 

We have opted to add `save_MOM6_internal_state` as a subroutine in `MOM.F90`, and to call it from each of the drivers. We hope this will allow for more new packages to write restart files in the future. 

I have tested these additions for `solo_driver` and `FMS_cap`, but I don't have access to the other drivers, so I haven't been able to test them. 

cc @adcroft

### CODE REVIEW

**Comment by cspencerjones** [comment]
Since Alistair is one of the authors of this PR, it probably doesn't make sense for him to be a reviewer. Can you assign someone else @marshallward ?

**Review by Hallberg-NOAA — APPROVED** [review]
This seems to me like a reasonable solution to the problem with calling the routines to save the restart files for submodules that are known to MOM6 but not to the driver, as discussed in the description of this PR. As noted in the comments in this commit, there is more work to be done along these lines, but this is a viable way-point in the code changes.  This can be merged into dev/gfdl in due course, once the pipeline regression testing has passed.

**Comment by marshallward** [comment]
Given that this changes the drivers, which needs consultation with the partners, should we just push ahead with the suggested TODO plan and introduce `save_MOM_restart` which calls `save_restart`?

I can work on this and submit it as a PR to this PR.

**Comment by cspencerjones** [comment]
I'm happy for you to do that @marshallward , as long as it doesn't take months and months.

**Comment by marshallward** [comment]
I've submitted a potential revision to this PR which does the following:

* merges `save_restart` and `save_MOM6_internal_state` into a generalized restart function.

* Removes `MOM_restart` dependencies from the primary model driver code.  (It is still present in the surface forcing modules).

The PR is here for review: https://github.com/cspencerjones/MOM6/pull/1

It's potentially disruptive, so I expect it needs careful review before merging.  If it's too much, then maybe we can leave it for a later date.

**Review by marshallward — APPROVED** [review]
We can take this as-is, and the suggested amendments will be handled in a separate PR.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/19805 :heavy_check_mark:

**Comment by cspencerjones** [comment]
Thanks very much @marshallward !!

**Pull request merged**
