### PR TITLE
interface for MOM_interp_infra

### PR DESCRIPTION
**Pull request by raphaeldussin**

### CODE REVIEW

**Comment by raphaeldussin** [comment]
@Hallberg-NOAA this should be working pretty soon, please squash and merge

**Review by Hallberg-NOAA — COMMENTED** [review]
Thank you for this PR that provides explicit interfaces and documentation for the horizontal interpolation routines.

My once concern here is that we have made the decision that we will only add interfaces for the versions that are actually used by MOM6, not all of the variants that are provided by FMS. I suspect that some of the variants that were introduced to MOM_interp_infra.F90 are not actually being used, and hence can be removed.

**Comment by raphaeldussin** [comment]
@Hallberg-NOAA  the unused interfaces are removed now.

**Comment by Hallberg-NOAA** [comment]
This PR is being tested with https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11995, and it should be merged (as a squash merge because a number of the intermediate commits encountered errors) as soon as the pipeline testing has passed.

**Review by Hallberg-NOAA — APPROVED** [review]
These changes do a very nice job of documenting the interpolation interfaces, and I think that the new names do a much better job of describing what the routines in question actually do.  Now that it has passed all of the TC and pipeline testing, I am happy approve this PR, although the actual merge of this PR should be a squash-merge due to the intermediate commits that had problems exposed by the testing.

**Pull request merged**
