### PR TITLE
Better variables for updated masks in fill_miss_2d

### PR DESCRIPTION
**Pull request by Hallberg-NOAA**
Within fill_miss_2d, there are 2 sets of masked values used for remapping - masked values in neighboring points in arbitrary units (with names like "south") and the updated valid mask with values of 0 or 1 (with names like "gs").  At one point in the code, the former were being used where the latter were more appropriate.  This commit changes this to help with the understandability of the code.  All answers and output are bitwise identical.

### CODE REVIEW

**Review by marshallward — APPROVED** [review]
I agree that this follows the intended use of the variables.

**Review by adcroft — CHANGES_REQUESTED** [review]
PGI (nVidia) has a regression in OM4_025 and other experiments. See https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/jobs/126178

**Comment by Hallberg-NOAA** [comment]
I don't see how to revise this proposal to avoid these changes in answers with the pgi (nVidia) compiler.  After looking into this in detail, the answer changes only occur in cases that use an older formulation that does a 5-point sum without any parentheses.  This give the compiler the ability to rearrange this sum at will, and the nVidia compiler appears to be doing so based on considerations that are not apparent to me.  However, when the newer (rotationally symmetric) but mathematically equivalent form with parentheses that specify the order of operations are used, the answers are preserved for all of the compilers.

**Comment by Hallberg-NOAA** [comment]
I have revised this commit to avoid the Nvidia changes by only changing which variables we are using when the relevant `answer_date` argument is high enough that the order of arithmetic is specified.  I also slightly refactored this code at the same time to move the logical test on `ans_2018` is outside of the i- and j- do loops.

**Review by marshallward — APPROVED** [review]
While it would be nice to better understand why a variable swap would change the order of arithmetic (if that is even what is happening here), I suppose it does not much matter in the end, and this will preserve the solutions.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/23564 :heavy_check_mark:

**Review by marshallward — APPROVED** [review]

**Pull request merged**
