### PR TITLE
+add h to drifters interface

### PR DESCRIPTION
**Pull request by cspencerjones**
This commit brings the drifters interface up-to-date with the current version of the drifters package, which requires h (layer thickness) to calculate the vertical movement of particles. The interfaces in the code and in config_src/external are updated to pass this information to the drifters package.

### CODE REVIEW

**Comment by cspencerjones** [comment]
Thanks - is this ok? Or were you looking for something more?

**Review by MJHarrison-GFDL — CHANGES_REQUESTED** [review]
Hi Spencer!   You can look at other routines to template this. Layer thickness  are denoted [H ~> m or kg m-2] , temperature is [C ~> degC], salt is [S ~> ppt], time is [T ~> s].     Sorry to be a nuisance here.

**Comment by marshallward** [comment]
Some other style comments:

* Indentation should be 2-space.  I see many instances of 1-space, 3-space and 4-space. e.g.
  ```
      if (CS%use_particles) then
          call particles_to_z_space(CS%particles,h)
      endif
  ```
  ```
    if (CS%use_particles) then
       call particles_to_k_space(CS%particles,h)
    endif
  ``  

* Commas should usually be followed by a space, e.g. 
  ```
  subroutine particles_init(parts, Grid, Time, dt, u, v,h)
  ```
  ```
  use MOM_particles_mod,         only : particles_to_k_space,particles_to_z_space
  ```
  (Array indexing is an exception)
  
More than you could want to know at the [style guide](https://github.com/NOAA-GFDL/MOM6/wiki/Code-style-guide).  As Matt said, sorry to be a nuisance.

**Comment by cspencerjones** [comment]
Thanks @marshallward and @MJHarrison-GFDL ! I hope I caught everything. Now I'll know better what to look for next time.

**Review by MJHarrison-GFDL — APPROVED** [review]
Thank you for making those changes Spencer. This PR looks good .

**Review by MJHarrison-GFDL — APPROVED** [review]

**Review by marshallward — APPROVED** [review]

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/jobs/106995 :heavy_check_mark:

**Pull request merged**
