### PR TITLE
Brankart PGF update

### PR DESCRIPTION
**Pull request by adcroft**
- Adds a diagnostic of the parameterized SGS temperature variance
- Updates the estimate of grid-scale variance, replacing a gradient-along-coordinate squared form by a thickness-weighted least-squares fit. The latter handles coordinates collapsed against topography much better and addresses the spurious behavior we were seeing.

### CODE REVIEW

**Comment by adcroft** [comment]
Closing to solve a restart problem that appeared with the merge

**Comment by Hallberg-NOAA** [comment]
This PR changes answers in some test cases (e.g., TC2 in .testing), although it does not change any answers in the MOM6-examples test suite. This should have been noted in the comments describing this PR.

**Review by Hallberg-NOAA — APPROVED** [review]
I have examined these code changes and tested them, and I am convinced that this PR should be merged into dev/gfdl.

**Comment by marshallward** [comment]
Gaea regression test: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/11144

**Pull request merged**
