### PR TITLE
Fixed downsampling for x:sum y:point z:point diags

### PR DESCRIPTION
**Pull request by jkrasting**
- previous code had averaging instead of summation for
  SPP (x:sum,y:point,z:point) diagnostics
- corrects an issue where these diagnostics were incorrect
  by approximately a factor of 2.
- Orginially found when analyzing the depth-integrated
  temperature advection diagnostic (T_ady_2d)

### CODE REVIEW

**Comment by raphaeldussin** [comment]
do we need a similar fix for https://github.com/NOAA-GFDL/MOM6/blob/6d4a4839070bc599fe03551b2d6fa6f53fe16584/src/framework/MOM_diag_mediator.F90#L4170 ?

**Comment by jkrasting** [comment]
Not sure. Feel free to update my commit though.
--

**Comment by Hallberg-NOAA** [comment]
I agree that we do also need the other corrections on the lines that @raphaeldussin noted.

While we are at it, for clarity when reading the code we might want to replace the variable "ave" with a new variable "sum" in these cases and eliminate the now-unused variable "total_weight" in these cases.

**Review by Hallberg-NOAA — APPROVED** [review]
I agree that these changes correct important bugs in the reduced-grid diagnostic output.

**Comment by Hallberg-NOAA** [comment]
This PR passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/12421.

**Pull request merged**
