### PR TITLE
User/bgr/epbl len

### PR DESCRIPTION
**Pull request by breichl**
New EPBL version where MSTAR no longer must be treated as a constant.

- Adds pass of buoyancy flux to EPBL (needed to compute MO length scale)
- Adds calculation of variable MSTAR to EPBL (option is added to revert to use constant)
- MSTAR calculation is based on MLD and composite Ekman/Monin-Obuhkov length scale.
- Relationship between the length scale and MSTAR is determined to be roughly linear and optional inputs for line parameters are added (with defaults based on fit to K-epsilon simulations).
- Reworks EPBL MLD iteration to use MLD value determined by EPBL rather than simple value based on vertical TKE decay (this may require more robust testing but it is a necessary change since MLD must now be estimated more precisely).
- Adds input for exponent in EPBL mixing length (default 1, was 2)

### CODE REVIEW

**Comment by adcroft** [comment]
FTR, @breichl tells me the new optimal settings will be:
```
MSTAR_FIXED = False
NSTAR = 0.08
TKE_DECAY = 0.01
USE_MLD_ITERATION = True
ORIG_MLD_ITERATION = False
EPBL_TRANSITION_SCALE = 0.01
MIX_LEN_EXPONENT = 1.0
```

**Comment by adcroft** [comment]
@breichl , answers for OM4_05 a nd OM4_025 are changed?

**Comment by breichl** [comment]
I modified 2 changes to the MLD iteration guesses so previous ePBL version values are used as the default now.  This very likely contributed to changing answers in default setting.

**Comment by adcroft** [comment]
Can we recover the old answers with a flag?

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Pull request merged**
