### PR TITLE
Obsolete the HENYEY_IGW_BACKGROUND_NEW option.

### PR DESCRIPTION
**Pull request by kshedstrom**
As discussed in the dev call today, make HENYEY_IGW_BACKGROUND_NEW obsolete.

### CODE REVIEW

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
When an option is made obsolete, it should be removed from the the model code (outside of find_obsolete_params), and all of the code that is used exclusively with that option should also be deleted.

Also, because HENYEY_IGW_BACKGROUND_NEW is used to set a logical variable, the right call to obsolete it in find_obsolete_params would be `call obsolete_logical(param_file, "HENYEY_IGW_BACKGROUND_NEW")`.  We might also consider adding the optional argument  `, warning_val=.False.)`.

**Comment by kshedstrom** [comment]
Thanks for the feedback!

**Review by Hallberg-NOAA — APPROVED** [review]

**Comment by Hallberg-NOAA** [comment]
This has passed pipeline testing at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/16746, but it does change the contents of some MOM_parameter_doc files.

**Comment by marshallward** [comment]
@kshedstrom OK to squash this one?

**Comment by marshallward** [comment]
Nevermind, I see that it's already been merged into dev/ESMG.

In order to preserve the dev/ESMG history, this needs to be merge-commited.

**Pull request merged**
