### PR TITLE
*Initialize modal structure array for wave speed

### LINKED ISSUE #508: 1/2 degree ocean-ice models does not reproduce across restarts
In tag dev/master/2017.05.26 there is a restart issue with 1/2 degree models. 

This has to do with the default value of the parameter KHTH_USE_EBT_STRUCT that has changed in this tag from "False" to "True". Indeed changing it via an override back to "False" make the models reproduce again.

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
This will change answers for test cases using MEKE
  with KHTH_USE_EBT_STRUCT = T. Fixes #508

### CODE REVIEW

**Comment by adcroft** [comment]
Great!

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by nikizadehgfdl** [comment]
This resolved the restart issue for 1/2 degree ocean-ice model. Thanks.

**Comment by adcroft** [comment]
Good. I'll run this (and Bob's PR) through the pipe and then we can finally
merge it all onto dev/master ready for a new tag.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by adcroft** [comment]
@MJHarrison-GFDL Am I right in saying this only changes land values of modal_structure(:,:,:) ? If so, why not set to 0.0 instead of 1.0 ?

Or is it changing the values in vanished layers at the bottom? In which case we most definitely should have 0.0 ...

**Comment by adcroft** [comment]
Shall I make the change to initialize to 0.0?

**Pull request merged**
