### PR TITLE
Adds the Bodner et al. 2023 version of MLE 

### PR DESCRIPTION
**Pull request by abodner**
This PR involves the implementation of the Bodner 2023 submesoscale scheme to include new frontal width scaling with dependence on surface atmospheric forcing parameters via the ePBL scheme. The new scheme reveals non-zero changes in the mixed layer depth, in particular shoaling of the mixed layer depth in the lower latitudes and deepening in higher latitudes. 
MLD changes

### CODE REVIEW

**Comment by marshallward** [comment]
The performance test is failing because its internal `MOM_input` parser doesn't support nested parameters (`MLE%`... `%MLE`), and this patch introduces a new one.

Similarly, the other regressions are likely due to the modification of the `tc2.a` test.

I will fix the perf test script, but for now we can just override this test (which is not actually much of a test anyway).

**Comment by marshallward** [comment]
I believe that #353 will fix the issue in the Performance Monitor test.

**Comment by abodner** [comment]
Thanks for the update!

**Comment by Hallberg-NOAA** [comment]
Thank you, @abodner, for this valuable and very well documented commit.  We will be approving this commit and merging into dev/gfdl shortly, just as soon as we figure out the cleanest way to resolve the very minor code conflicts with the latest version of dev/gfdl and run it through our newly refurbished automated testing.

**Review by Hallberg-NOAA — APPROVED** [review]
Thank you for this contribution.

 Everything looks correct upon visual inspection of the code changes, apart from some minor problems with the documentation of a few the rescaled units of the new variables in the new code, but these can be corrected with a follow-up commit, perhaps while these routines are being adapted to work in fully non-Boussinesq mode.

 The version of this PR with resolved conflicts has passed the pipeline testing (with the expected additions to the runtime parameters in the MOM_parameter_doc files)  at https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/19331

**Comment by marshallward** [comment]
For somewhat boring technical reasons, the CI was re-run for this PR:

https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/19335 :heavy_check_mark: :yellow_circle:

This will be handled as a merge rather than a rebase, in order to better preserve the valuable content in the PR discussion.

**Comment by abodner** [comment]
Thanks all!

**Pull request merged**
