### PR TITLE
ice-sheet/ocean coupling for misomip

### PR DESCRIPTION
**Pull request by alex-huth**
This PR includes the remaining changes needed to successfully run the MISOMIP IceOcean tests for a coupled ocean and dynamic ice-sheet.

Several changes rwere equired for perfect restarts during coupled ice-sheet/ocean runs: (1) added visc%taux and visc%tauy to the ocean restart file; (2) ice sheet geometry is now updated before (rather than after) calculating ice shelf fluxes and pressure to ocean; and (3) corrected the calculation of ISS%mass_shelf for ice-shelf cells that are partially-filled with ice during advection of the ice front.

Also modified the scheme that maintains a nearly constant sea level in coupled ice-sheet/ocean runs by applying ocean balancing fluxes to offset changes in ice-sheet pressure on the ocean. This scheme now accounts for the case where some of the ice sheet is grounded, and the a new parameter CONST_SEA_LEVEL_MISOMIP was added to specifically apply the balancing flux over the MISOMIP sponge region only. These changes also required calculation of ice sheet dH/dt, which can now be saved as a useful diagnostic field for any ice sheet simulation.

### CODE REVIEW

**Review by Hallberg-NOAA — APPROVED** [review]
These changes look good to me.

**Comment by marshallward** [comment]
@alex-huth Merging #513 first seems to have caused a conflict here, could you fix this?

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/21252 :heavy_check_mark:

**Comment by marshallward** [comment]
I can see these commits are meaningful, but there are some conflicts in some of the commits, so I think I will squash-merge these.  @alex-huth is that ok?

**Comment by alex-huth** [comment]
@marshallward yes, please squash

**Pull request merged**
