### PR TITLE
Obc tracers, part 1

### PR DESCRIPTION
**Pull request by kshedstrom**
Adding code for an OBC tracer registry on the segments. I believe this is working for T and S. It changes answers for CCS because it changes behavior in the tracer advection scheme on the open boundaries.

- This code is incomplete in that other tracers aren't being handled completely yet and must change the DOME tracers, though that doesn't change the answers being checked.
- Next up is to have the 3-d tracer registry register the OBC tracers should there be any. This has to happen there to keep the tracer index count correct where it is used in the advection scheme. Note that this potentially happens before we have the tracer values, requiring a later setting of the OBC tracer values (see temp and salt as an example of this).
- Some random tracer doxygen, also incomplete.

### CODE REVIEW

**Comment by kshedstrom** [comment]
Am I the only one getting Travis failures these days? I think it's an FMS versioning issue:
../../src/framework/MOM_time_manager.F90:19.36:

```
use time_interp_external_mod, only : get_external_field_axes, get_external_fiel
                                    1

Error: Symbol 'get_external_field_axes' referenced at (1) not found in module 'time_interp_external_mod'
../../src/framework/MOM_time_manager.F90:19.61:
use time_interp_external_mod, only : get_external_field_axes, get_external_fiel
                                                             1
```

**Comment by MJHarrison-GFDL** [comment]
I don't see that error in the Travis logs. Appears to have stalled running double gyre w/ 4 cores

**Comment by adcroft** [comment]
I restarted the build...

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/2546

**Pull request merged**
