### PR TITLE
Adding Langmuir parameterizations and methods to obtain Stokes drift in MOM

### PR DESCRIPTION
**Pull request by breichl**
- Implements new module MOM_wave_interface which includes various methods to obtain Stokes drift for use in Langmuir turbulence parameterizations in MOM including reading from files, prescribed profiles, and parametric profiles.
- Coupled driver ocean_model_MOM modified to control input of Stokes drift data.
- Solo driver MOM_driver modified to control input of Stokes drift data.
- MOM.F90 modified to pass wave control structure through to dynamics and thermodynamics as optional term.
- MOM_dynamics_unsplit modified to pass wave control structure as optional term.
- MOM_diabatic_driver modified to pass wave control structure to KPP or ePBL as optional term.
- Implements new Langmuir turbulence options in KPP.
- Modifies KPP routine so Vt2 term in bulk Richardson number can be modified by MOM_KPP (for Langmuir enhancement).
- Modifies Langmuir number approach for ePBL (moves Stokes drift/Langmuir number subroutines from ePBL to MOM_wave_interface).
- Adds ability to do "Lagrangian" (Stokes + Eulerian) mixing in MOM_vert_friction (needed for some KPP Langmuir experiments).
- Fixed bug in CVmix_tests wind stress definition (feature is untested in present suite so no answer change).

- This p/r should not change answers.

### CODE REVIEW

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/3566

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/3706

**Comment by adcroft** [comment]
Something about the OM4 setups was sensitive. From the log:
```
ice_ocean_SIS2/Baltic_OM4_025/ocean.stats.gnu: FAILED
ice_ocean_SIS2/Baltic/ocean.stats.gnu: OK
ice_ocean_SIS2/OM4_025/ocean.stats.gnu: FAILED
ice_ocean_SIS2/Baltic_OM4_05/ocean.stats.gnu: FAILED
ice_ocean_SIS2/SIS2/ocean.stats.gnu: OK
ice_ocean_SIS2/OM4_05/ocean.stats.gnu: FAILED
```

**Comment by breichl** [comment]
Okay.  I suspect its related to the existing ePBL Langmuir scheme in the OM4 configurations.

**Comment by adcroft** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/pipelines/3740

**Pull request merged**
