### PR TITLE
Allow incorrect PPM:H3 tracer advection stencil

### PR DESCRIPTION
**Pull request by marshallward**
Due to answer changes in multiple production experiments, this patch introduces a new parameter, ~USE_HUYNH_STENCIL_REGRESSION~ USE_HUYNH_STENCIL_BUG, which sets the tracer advection stencil width to its previous incorrect value.  This parameter replicates the previous method, which keeps `stencil` at 2 when PPM:H3 is used.

----

The logical parameters are

* P = CS%usePPM
* H = CS%useHuynh
* E = USE_HUYNH_STENCIL_REGRESSION
* R = CS%useHuynhRegression

The three expressions of interest:

1. P & ~H
2. P
3. P & ~R

(1) is the original incorrect expression, (2) is the fixed expression, and (3) is the proposed update.

What we want:

If E is false, then (3) should reduce to (2).  If E is true, then (3) should reduce to (1).

R is computed as follows:

* R = False  (from derived type initialization)
* if (H) R = E  (from get_param call)

This is equivalent to R = H & E, and (3) is P & ~(H & E).

* If E is False, then P & ~(H & False) = P.
* If E is True, then P & ~(H & True) = P & ~H

So this flag should replicate both the previous and current behavior.

### CODE REVIEW

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/jobs/133166 :heavy_check_mark: :yellow_circle: 

(Param files are a bit garbled, but the new parameter will end up changing them.)

**Review by Hallberg-NOAA — CHANGES_REQUESTED** [review]
Overall this PR seems to correct the problem, but rather than calling the new runtime parameter a "..._REGRESSION", I would prefer that we call it "..._BUG" to clearly indicate that the old version is inconsistent across PE counts and layouts, and hence to use it is to use code with a known bug.

**Comment by marshallward** [comment]
I always felt "bug" was a rather gauche term, but youdaboss.  I'll get it in ASAP.

**Review by Hallberg-NOAA — APPROVED** [review]
I approve this change as revised.

**Pull request merged**
