### PR TITLE
Bugfix: a couple of mask_depth related issues

### PR DESCRIPTION
**Pull request by herrwang0**
This PR addresses a couple of bugs related to `MASKING_DEPTH`.

1. In subroutine `limit_topography`, value of `D` over the land is re-assigned to `mask_depth` (previously untouched). This is required for cases with masked-out land PEs. When topography is read from a file, `D` is initialized with a large number (-9.e30) https://github.com/NOAA-GFDL/MOM6/blob/0abf9c2b63e61980382457cc1b448904d7f36784/src/initialization/MOM_shared_initialization.F90#L170 , this number stays in the halo regions of the masked PEs. The fix avoids NaN's in global check-sums.  This is first reported by @favorliao in https://github.com/NOAA-GFDL/MOM6/pull/1428 
2. Local variable `Dmin` in subroutine `initialize_masks` is renamed to `Dmask` to clarify the difference between `min_depth` and `mask_depth`
3. A zero `mask_depth` was implicitly used in subroutine `apply_topography_edits_from_file`. The fix here should address issue #1419

### CODE REVIEW

**Review by marshallward — APPROVED** [review]
I agree with these changes, and also with restructuring `initialize_masks` around `mask_depth` rather than `min_depth`.

**Comment by marshallward** [comment]
https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/13297 :heavy_check_mark: :yellow_circle:

**Comment by adcroft** [comment]
@herrwang0 That's a relief! I was worried you were using the "old" pathway with MASKING_DEPTH=-9999. The changed code block with `0.5*min_depth` inside that old path made me wonder if you were using it.

**Comment by adcroft** [comment]
I agree, but you don't reach either half if you set MASKING_DEPTH - the whole of that excerpt is only for when MASKING_DEPTH is not set. I think you're the only one trying so far and I think using MASKING_DEPTH as you are if the better pathway.

**Comment by herrwang0** [comment]
@adcroft Thanks so much for doing this! It is complicated with these two somewhat independent variables here, and extra work is needed to take into consideration of almost all the scenarios, to make all parties happy.

**Pull request merged**
