### PR TITLE
 Fixing issue #539

### PR DESCRIPTION
**Pull request by kshedstrom**
There are two places in the code where USE_BODNER23 is checked. They have to be consistent. This fixes the inconsistency I had mentioned in #539 , but does introduce an extra
```
MLE%
%MLE
```
into the output doc files.

### CODE REVIEW

**Comment by marshallward** [comment]
I don't think this patch is quite doing what we want.  From my reading, it's implicitly creating `MLE%MLE%USE_BODNER23`, which is equivalent to
```
MLE%
MLE%USE_BODNER23
%MLE
```
I think the only real fix here is to get the parser to properly read the contents of `MLE% ... %MLE`.

**Comment by kshedstrom** [comment]
No, this properly parses
```
MLE%
USE_BODNER23
%MLE
```

**Comment by marshallward** [comment]
Ah sorry.... I think I confused myself.  Maybe that's why `cs%use_bodner` was never set.

@adcroft Does this look ok?

**Comment by marshallward** [comment]
I've checked this in tc2.a and both forms work and give the same answer with this patch.

**Comment by marshallward** [comment]
I spoke with @adcroft and he agreed that this is the preferred method of accessing parameter block contents.

There was a thought that `get_param(..., "MLE%USE_BODNER23", ...)` still ought to work, despite some potential ambiguity of the "top" parameter block (e.g. what if we were inside `KPP%`?).  But it's clearly broken as-is and also not the preferred method, so we will just leave it for another time.

Our test machine Gaea is being turned upside down today, but I'll try to get this tested and merged ASAP.

**Review by marshallward — APPROVED** [review]

**Comment by marshallward** [comment]
We think there still may be a minor issue with the new `open`/`closeParameterBlock` function calls.  This new solution appears to be printing an empty `MLE%`/`%MLE` block in the `MOM_parameter_doc.all` files.

At the least, we might need to add support for `do_not_log=` to `openParameterBlock`.  We might also want to consider further restructuring of the parameter blocks.

**Comment by marshallward** [comment]
#558 should eliminate the redundant `MLE%` `%MLE` block records.

**Comment by marshallward** [comment]
I've run a modified version of this PR which appears to fix the problem and does not produce a redundant `MLE%`/ `%MLE`.  It is now passing our tests with no parameter regression.

I will merge this directly to MOM6 and close this issue once it's been finalized.

----

Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/MOM6/-/pipelines/22146 :heavy_check_mark:

**Comment by marshallward** [comment]
Matching commit: https://github.com/NOAA-GFDL/MOM6/commit/5ca70bac6dd4306a0e1d3b5c653aa679ac4e4fa4

**Pull request closed without merging**
