### PR TITLE
Fortran 2023 compliance and testing

### PR DESCRIPTION
**Pull request by marshallward**
This PR contains several commits to ensure Fortran 2023 compliance.

Most changes are related to missing or redundant commas in I/O statements.  Others were related to the ordering of input-dependent arguments in functions.

This should help improve support on other compilers which have more strict I/O syntax requirements.  It will also help prepare us to turn on additional warnings and improve the overall testing of the model.

It also includes modifications to the GitHub CI to provide F2018 testing.  (Unfortunately our compiler of choice is a bit out of day and cannot yet provide 2023 compliance testing.)

### CODE REVIEW

**Review by Hallberg-NOAA — COMMENTED** [review]
I agree with most of these changes, but I am a bit confused by the changes in posix.F90, in which a `read` call is made for several otherwise unused `intent(in)` variables after the `error stop` calls.

  The new `read` calls will never be reached, so in some sense what they do is irrelevant, but what I am wondering about is whether some compilers might object to doing `read` calls that would change the values of these `intent(in)` variables.  I have spent some time reading in detail about the meaning of `intent(in)`, and it looks to me like this should be illegal.  Is there some other fake operation that we could do with these variables (e.g., call `write` instead of `read`) that would be more consistent with the declared intent of these variables?

**Comment by marshallward** [comment]
The statements themselves are a bit misleading.  When no IO control data is specified with `(..)`, the `READ fmt` is using the first argument as a format string, not as a source or target for I/O.  They are the analogue of `print (...)` or `print *`.  So they are being read (as `intent(in)`), and any false positive warnings are suppressed.

Obviously it's a dumb construct and I wish there were a better way to handle it, but I don't believe it will be a problem.

**Comment by Hallberg-NOAA** [comment]
Thanks for that explanation about how `read` is being used.  All is not clear to me.

**Review by Hallberg-NOAA — APPROVED** [review]
This all looks reasonable to me.

**Comment by marshallward** [comment]
Gaea regression: https://gitlab.gfdl.noaa.gov/ogrp/mom6ci/MOM6/-/pipelines/24907 :heavy_check_mark:

**Pull request merged**
